/*
 * Emit Win32.WebView ergonomic widget from WebView2MethodCatalog + shell template.
 */

namespace Generate {
	public class ErgoWebView2Emitter : Object {
		const string GENERATED_HEADER = """/* Generated by generate-binding — do not edit. */

""";

		const string SIGNALS_MARKER = "/* @WEBVIEW2_SIGNALS@ */";
		const string CONSTRUCTOR_PARAMS_TOKEN = "@CONSTRUCTOR_PARAMS@";
		const string EVENT_WIRING_MARKER = "/* @EVENT_WIRING@ */";
		const string CATALOG_MARKER = "/* @WEBVIEW2_CATALOG@ */";

		class ErgoProperty : Object {
			public string name { get; construct set; default = ""; }
			public string? get_glue { get; set; default = null; }
			public string? put_glue { get; set; default = null; }
			public WebView2GlueKind get_kind { get; set; default = WebView2GlueKind.SKIP; }
		}

		struct ShellProfile {
			string constructor;
			Gee.ArrayList<Parse.ErgoNativeMapEntry> entries;
		}

		/** Minimal cross-unit C header (Vala emits #include from other .vala in the same target). */
		public static string emit_c_header() {
			return """/* Generated by generate-binding — do not edit.
 * Cross-unit include for Vala sources that use Win32.WebView from generated/win32-ergo-webview2.vala.
 * Keep minimal: each .c unit emits its own GObject types and method declarations. */

#ifndef VALA_WIN32_ERGO_WEBVIEW2_H
#define VALA_WIN32_ERGO_WEBVIEW2_H

#include <glib-object.h>
#include <windows.h>

#endif

""";
		}

		public string emit(
			WebView2MethodCatalog catalog,
			string conventions_path,
			string template_path
		) throws GLib.Error {
			var shell = load_shell_profile(conventions_path);
			return emit_class(catalog, shell, template_path);
		}

		static ShellProfile load_shell_profile(string conventions_path) throws GLib.Error {
			var data = ShellProfile();
			data.constructor = "Window parent, int x, int y, int width, int height";
			data.entries = new Gee.ArrayList<Parse.ErgoNativeMapEntry> ();
			var parser = new Json.Parser();
			parser.load_from_file(conventions_path);
			var root = parser.get_root();
			if (root == null || root.get_node_type() != Json.NodeType.OBJECT) {
				throw new GLib.IOError.FAILED("conventions root must be object");
			}
			var profiles = root.get_object().get_member("profiles");
			if (profiles == null || profiles.get_node_type() != Json.NodeType.OBJECT) {
				return data;
			}
			var profiles_obj = profiles.get_object();
			if (!profiles_obj.has_member("WebView2")) {
				return data;
			}
			var webview2 = profiles_obj.get_member("WebView2").get_object();
			var ctor_node = webview2.get_member("constructor");
			if (ctor_node != null && ctor_node.get_value_type() == typeof (string)) {
				data.constructor = ctor_node.get_string();
			}
			var map_node = webview2.get_member("ergo_native_map");
			if (map_node == null || map_node.get_node_type() != Json.NodeType.ARRAY) {
				return data;
			}
			var arr = map_node.get_array();
			for (uint i = 0; i < arr.get_length(); i++) {
				var entry = Json.gobject_deserialize(
					typeof (Parse.ErgoNativeMapEntry),
					arr.get_element(i)
				) as Parse.ErgoNativeMapEntry;
				if (entry != null) {
					data.entries.add(entry);
				}
			}
			return data;
		}

		string emit_class(
			WebView2MethodCatalog catalog,
			ShellProfile shell,
			string template_path
		) throws GLib.Error {
			string body;
			GLib.FileUtils.get_contents(template_path, out body);
			body = strip_template_preamble(body);

			var signals_sb = new GLib.StringBuilder();
			foreach (var entry in shell.entries) {
				if (entry.kind == "signal") {
					signals_sb.append(emit_signal(entry.ergo));
				}
			}

			var catalog_sb = new GLib.StringBuilder();
			emit_catalog_methods(catalog_sb, catalog, catalog.host_overrides);
			emit_catalog_properties(catalog_sb, catalog, catalog.host_overrides);

			body = body.replace(CONSTRUCTOR_PARAMS_TOKEN, shell.constructor);
			body = replace_marker(body, SIGNALS_MARKER, signals_sb.str);
			body = replace_marker(body, EVENT_WIRING_MARKER, emit_event_wiring_body(shell.entries));
			body = replace_marker(body, CATALOG_MARKER, catalog_sb.str);

			return GENERATED_HEADER + body;
		}

		static string strip_template_preamble(string body) {
			if (!body.has_prefix("/*")) {
				return body;
			}
			var end = body.index_of("*/");
			if (end < 0) {
				return body;
			}
			var i = end + 2;
			while (i < body.length) {
				var c = body[i];
				if (c != '\n' && c != '\r') {
					break;
				}
				i++;
			}
			return body.substring(i);
		}

		static string replace_marker(string body, string marker, string content) {
			var at = body.index_of(marker);
			if (at < 0) {
				throw new GLib.IOError.FAILED(@"template missing $(marker)");
			}
			return body.substring(0, at) + content + body.substring(at + marker.length);
		}

		static string emit_event_wiring_body(Gee.ArrayList<Parse.ErgoNativeMapEntry> entries) {
			var sb = new GLib.StringBuilder();
			foreach (var entry in entries) {
				if (entry.kind != "signal") {
					continue;
				}
				var signal_name = parse_signal_name(entry.ergo);
				if (signal_name == null) {
					continue;
				}
				var bind_name = "bind_" + signal_name;
				if (entry.ergo.contains("bool")) {
					sb.append_printf(
						"""		Ui.WebView.%s ((success) => {
			%s(success);
		});
""",
						bind_name,
						signal_name
					);
				} else {
					sb.append_printf(
						"""		Ui.WebView.%s (() => {
			%s();
		});
""",
						bind_name,
						signal_name
					);
				}
			}
			return sb.str;
		}

		static string? parse_signal_name(string ergo) {
			var trimmed = ergo.strip();
			var open = trimmed.index_of("(");
			if (open < 0) {
				return trimmed.length > 0 ? trimmed : null;
			}
			var name = trimmed.substring(0, open).strip();
			return name.length > 0 ? name : null;
		}

		static void emit_catalog_methods(
			GLib.StringBuilder sb,
			WebView2MethodCatalog catalog,
			WebView2HostOverrides overrides
		) {
			foreach (var entry in catalog.entries) {
				if (overrides.is_ergo_skipped(entry.glue_name)) {
					continue;
				}
				switch (entry.glue_kind) {
				case WebView2GlueKind.WEBVIEW_VOID:
					emit_void_method(sb, entry.glue_name);
					break;
				case WebView2GlueKind.WEBVIEW_STRING:
					if (overrides.is_ergo_bool_method(entry.glue_name)) {
						emit_bool_string_method(sb, entry.glue_name);
					} else {
						emit_void_string_method(sb, entry.glue_name);
					}
					break;
				case WebView2GlueKind.WEBVIEW_STUB:
					emit_bool_string_method(sb, entry.glue_name);
					break;
				case WebView2GlueKind.COM_SYNC_ONLY:
					if (entry.glue_name == "navigate") {
						emit_void_string_method(sb, "navigate", "string url", "url");
					}
					break;
				default:
					break;
				}
			}
		}

		static void emit_void_method(GLib.StringBuilder sb, string name) {
			var glue = "Ui.WebView." + name;
			sb.append_printf(
				"""	public void %s() {
		if (!attached || !%s()) {
			stderr.printf("WebView: %s failed\n");
		}
	}

""",
				name,
				glue,
				name
			);
		}

		static void emit_void_string_method(
			GLib.StringBuilder sb,
			string name,
			string? param_decl = null,
			string? param_name = null
		) {
			var arg = param_name ?? string_param_name(name);
			var decl = param_decl ?? ("string " + arg);
			var glue = "Ui.WebView." + name;
			sb.append_printf(
				"""	public void %s(%s) {
		if (!attached || !%s(%s)) {
			stderr.printf("WebView: %s failed\n");
		}
	}

""",
				name,
				decl,
				glue,
				arg,
				name
			);
		}

		static void emit_bool_string_method(GLib.StringBuilder sb, string name) {
			var arg = string_param_name(name);
			var glue = "Ui.WebView." + name;
			sb.append_printf(
				"""	public bool %s(string %s) {
		return attached && %s(%s);
	}

""",
				name,
				arg,
				glue,
				arg
			);
		}

		static void emit_catalog_properties(
			GLib.StringBuilder sb,
			WebView2MethodCatalog catalog,
			WebView2HostOverrides overrides
		) {
			var props = new Gee.HashMap<string, ErgoProperty> ();
			foreach (var entry in catalog.entries) {
				if (overrides.is_ergo_skipped(entry.glue_name)) {
					continue;
				}
				switch (entry.glue_kind) {
				case WebView2GlueKind.WEBVIEW_GET_COM_STRING:
				case WebView2GlueKind.WEBVIEW_GET_BOOL:
				case WebView2GlueKind.WEBVIEW_GET_DOUBLE:
					add_property_get(props, entry, overrides);
					break;
				case WebView2GlueKind.WEBVIEW_PUT_BOOL:
				case WebView2GlueKind.WEBVIEW_PUT_DOUBLE:
					add_property_put(props, entry, overrides);
					break;
				default:
					break;
				}
			}
			var names = new Gee.ArrayList<string> ();
			foreach (var key in props.keys) {
				names.add(key);
			}
			names.sort((a, b) => a.collate(b));
			foreach (var name in names) {
				emit_property(sb, props[name]);
			}
		}

		static void add_property_get(
			Gee.HashMap<string, ErgoProperty> props,
			WebView2CatalogEntry entry,
			WebView2HostOverrides overrides
		) {
			var name = overrides.ergo_property_name(entry.glue_name);
			if (!props.has_key(name)) {
				props[name] = new ErgoProperty() { name = name };
			}
			props[name].get_glue = entry.glue_name;
			props[name].get_kind = entry.glue_kind;
		}

		static void add_property_put(
			Gee.HashMap<string, ErgoProperty> props,
			WebView2CatalogEntry entry,
			WebView2HostOverrides overrides
		) {
			var name = overrides.ergo_property_name(entry.glue_name);
			if (!props.has_key(name)) {
				props[name] = new ErgoProperty() { name = name };
			}
			props[name].put_glue = entry.glue_name;
		}

		static void emit_property(GLib.StringBuilder sb, ErgoProperty prop) {
			if (prop.get_glue == null) {
				return;
			}
			var get_call = "Ui.WebView." + prop.get_glue;
			if (prop.put_glue != null) {
				var put_call = "Ui.WebView." + prop.put_glue;
				if (prop.get_kind == WebView2GlueKind.WEBVIEW_GET_DOUBLE) {
					sb.append_printf(
						"""	public double %s {
		get { return attached ? %s() : 1.0; }
		set {
			if (attached) {
				%s(value);
			}
		}
	}

""",
						prop.name,
						get_call,
						put_call
					);
				} else {
					sb.append_printf(
						"""	public bool %s {
		get { return attached && %s(); }
		set {
			if (attached) {
				%s(value);
			}
		}
	}

""",
						prop.name,
						get_call,
						put_call
					);
				}
				return;
			}
			switch (prop.get_kind) {
			case WebView2GlueKind.WEBVIEW_GET_COM_STRING:
				sb.append_printf(
					"""	public string %s {
		owned get { return attached ? %s() : ""; }
	}

""",
					prop.name,
					get_call
				);
				break;
			case WebView2GlueKind.WEBVIEW_GET_BOOL:
				sb.append_printf(
					"""	public bool %s {
		get { return attached && %s(); }
	}

""",
					prop.name,
					get_call
				);
				break;
			case WebView2GlueKind.WEBVIEW_GET_DOUBLE:
				sb.append_printf(
					"""	public double %s {
		get { return attached ? %s() : 1.0; }
	}

""",
					prop.name,
					get_call
				);
				break;
			default:
				break;
			}
		}

		static string emit_signal(string ergo) {
			var trimmed = ergo.strip();
			if (!trimmed.contains("(")) {
				return "	public signal void %s;\n\n".printf(trimmed);
			}
			var open = trimmed.index_of("(");
			var name = trimmed.substring(0, open);
			if (trimmed.contains("cancellable")) {
				return "	public signal void %s();\n\n".printf(name);
			}
			var close = trimmed.last_index_of(")");
			var params = trimmed.substring(open, close - open + 1);
			return "	public signal void %s%s;\n\n".printf(name, params);
		}

		static string string_param_name(string method) {
			if (method.has_suffix("_to_string")) {
				return "html";
			}
			if (method.has_prefix("post_web_message_as_")) {
				return "text";
			}
			if (method == "execute_script") {
				return "js";
			}
			if (method == "navigate") {
				return "url";
			}
			return "arg";
		}
	}
}
