/*
 * Emit Win32.WebView ergonomic widget from WebView2MethodCatalog + shell profile.
 */

namespace Generate {
	public class ErgoWebView2Emitter : Object {
		const string GENERATED_HEADER = """/* Generated by generate-binding — do not edit. */

using GLib;
using Win32.Ui.WebView;

namespace Win32 {

/**
 * Ergonomic WebView2 child — API from WebView2MethodCatalog; shell from profiles.WebView2.
 * One WebView per process today (Ui.WebView glue singleton).
 */
public class WebView : Widget {
""";

		const string GENERATED_FOOTER = """
}

}
""";

		class ErgoProperty : Object {
			public string name { get; construct set; default = ""; }
			public string? get_glue { get; set; default = null; }
			public string? put_glue { get; set; default = null; }
			public WebView2GlueKind get_kind { get; set; default = WebView2GlueKind.SKIP; }
		}

		struct ShellProfile {
			string constructor;
			Gee.ArrayList<Parse.ErgoNativeMapEntry> entries;
		}

		public string emit(WebView2MethodCatalog catalog, string conventions_path) throws GLib.Error {
			var shell = load_shell_profile(conventions_path);
			return emit_class(catalog, shell);
		}

		static ShellProfile load_shell_profile(string conventions_path) throws GLib.Error {
			var data = ShellProfile();
			data.constructor = "Window parent, int x, int y, int width, int height";
			data.entries = new Gee.ArrayList<Parse.ErgoNativeMapEntry> ();
			var parser = new Json.Parser();
			parser.load_from_file(conventions_path);
			var root = parser.get_root();
			if (root == null || root.get_node_type() != Json.NodeType.OBJECT) {
				throw new GLib.IOError.FAILED("conventions root must be object");
			}
			var profiles = root.get_object().get_object_member("profiles");
			if (profiles == null || !profiles.has_member("WebView2")) {
				return data;
			}
			var webview2 = profiles.get_object_member("WebView2");
			var ctor_node = webview2.get_member("constructor");
			if (ctor_node != null && ctor_node.get_value_type() == typeof (string)) {
				data.constructor = ctor_node.get_string();
			}
			var map_node = webview2.get_member("ergo_native_map");
			if (map_node == null || map_node.get_node_type() != Json.NodeType.ARRAY) {
				return data;
			}
			var arr = map_node.get_array();
			for (uint i = 0; i < arr.get_length(); i++) {
				var entry = Json.gobject_deserialize(
					typeof (Parse.ErgoNativeMapEntry),
					arr.get_element(i)
				) as Parse.ErgoNativeMapEntry;
				if (entry != null) {
					data.entries.add(entry);
				}
			}
			return data;
		}

		string emit_class(WebView2MethodCatalog catalog, ShellProfile shell) {
			var overrides = catalog.host_overrides;
			var sb = new GLib.StringBuilder(GENERATED_HEADER);
			foreach (var entry in shell.entries) {
				if (entry.kind == "signal") {
					sb.append(emit_signal(entry.ergo));
				}
			}
			sb.append("""
	public int x { get; private set; }
	public int y { get; private set; }
	public int width { get; private set; }
	public int height { get; private set; }
	private bool attached;
	private bool resize_with_parent;

""");
			emit_constructor(sb, shell.constructor);
			emit_event_handler_wiring(sb, shell.entries);
			emit_ready(sb, shell.entries);
			emit_layout(sb, shell.entries);
			emit_catalog_methods(sb, catalog, overrides);
			emit_catalog_properties(sb, catalog, overrides);
			emit_private_helpers(sb);
			sb.append(GENERATED_FOOTER);
			return sb.str;
		}

		static void emit_constructor(GLib.StringBuilder sb, string constructor) {
			sb.append_printf(
				"""	public WebView(
		%s,
		bool resize_with_parent = false
	) {
		base(parent);
		this.x = x;
		this.y = y;
		this.width = width;
		this.height = height;
		this.resize_with_parent = resize_with_parent;
		if (parent.handle == null || width <= 0 || height <= 0) {
			return;
		}
		parent.destroyed.connect(on_parent_destroyed);
		if (this.resize_with_parent) {
			parent.resized.connect(on_parent_resized);
		}
		if (!Ui.WebView.create_with_xywh(parent.handle, x, y, width, height, null)) {
			stderr.printf("WebView: create_with_xywh failed(runtime/loader missing?)\n");
			return;
		}
		attached = true;
		wire_event_handlers();
	}

""",
				constructor
			);
		}

		static void emit_event_handler_wiring(
			GLib.StringBuilder sb,
			Gee.ArrayList<Parse.ErgoNativeMapEntry> entries
		) {
			var has_signal = false;
			foreach (var entry in entries) {
				if (entry.kind == "signal") {
					has_signal = true;
					break;
				}
			}
			if (!has_signal) {
				return;
			}
			sb.append("""
	private void wire_event_handlers() {
""");
			foreach (var entry in entries) {
				if (entry.kind != "signal") {
					continue;
				}
				var signal_name = parse_signal_name(entry.ergo);
				if (signal_name == null) {
					continue;
				}
				var bind_name = "bind_" + signal_name;
				if (entry.ergo.contains("bool")) {
					sb.append_printf(
						"""		Ui.WebView.%s ((success) => {
			%s(success);
		});
""",
						bind_name,
						signal_name
					);
				} else {
					sb.append_printf(
						"""		Ui.WebView.%s (() => {
			%s();
		});
""",
						bind_name,
						signal_name
					);
				}
			}
			sb.append("\t}\n\n");
		}

		static string? parse_signal_name(string ergo) {
			var trimmed = ergo.strip();
			var open = trimmed.index_of("(");
			if (open < 0) {
				return trimmed.length > 0 ? trimmed : null;
			}
			var name = trimmed.substring(0, open).strip();
			return name.length > 0 ? name : null;
		}

		static void emit_ready(GLib.StringBuilder sb, Gee.ArrayList<Parse.ErgoNativeMapEntry> entries) {
			foreach (var entry in entries) {
				if (entry.kind == "lifecycle" && entry.ergo.strip() == "ready") {
					sb.append("""
	public bool ready {
		get { return attached && Ui.WebView.is_ready(); }
	}

""");
					return;
				}
			}
		}

		static void emit_layout(GLib.StringBuilder sb, Gee.ArrayList<Parse.ErgoNativeMapEntry> entries) {
			foreach (var entry in entries) {
				if (entry.kind == "layout") {
					sb.append("""
	/** Update layout in parent client coordinates (same pattern as MoveWindow children). */
	public void set_bounds(int x, int y, int width, int height) {
		this.x = x;
		this.y = y;
		this.width = width;
		this.height = height;
		push_layout();
	}

	public void move(int x, int y) {
		set_bounds(x, y, width, height);
	}

	public void resize(int width, int height) {
		set_bounds(x, y, width, height);
	}

""");
					return;
				}
			}
		}

		static void emit_catalog_methods(
			GLib.StringBuilder sb,
			WebView2MethodCatalog catalog,
			WebView2HostOverrides overrides
		) {
			foreach (var entry in catalog.entries) {
				if (overrides.is_ergo_skipped(entry.glue_name)) {
					continue;
				}
				switch (entry.glue_kind) {
				case WebView2GlueKind.WEBVIEW_VOID:
					emit_void_method(sb, entry.glue_name);
					break;
				case WebView2GlueKind.WEBVIEW_STRING:
					if (overrides.is_ergo_bool_method(entry.glue_name)) {
						emit_bool_string_method(sb, entry.glue_name);
					} else {
						emit_void_string_method(sb, entry.glue_name);
					}
					break;
				case WebView2GlueKind.WEBVIEW_STUB:
					emit_bool_string_method(sb, entry.glue_name);
					break;
				case WebView2GlueKind.COM_SYNC_ONLY:
					if (entry.glue_name == "navigate") {
						emit_void_string_method(sb, "navigate", "string url", "url");
					}
					break;
				default:
					break;
				}
			}
		}

		static void emit_void_method(GLib.StringBuilder sb, string name) {
			var glue = "Ui.WebView." + name;
			sb.append_printf(
				"""	public void %s() {
		if (!attached || !%s()) {
			stderr.printf("WebView: %s failed\n");
		}
	}

""",
				name,
				glue,
				name
			);
		}

		static void emit_void_string_method(
			GLib.StringBuilder sb,
			string name,
			string? param_decl = null,
			string? param_name = null
		) {
			var arg = param_name ?? string_param_name(name);
			var decl = param_decl ?? ("string " + arg);
			var glue = "Ui.WebView." + name;
			sb.append_printf(
				"""	public void %s(%s) {
		if (!attached || !%s(%s)) {
			stderr.printf("WebView: %s failed\n");
		}
	}

""",
				name,
				decl,
				glue,
				arg,
				name
			);
		}

		static void emit_bool_string_method(GLib.StringBuilder sb, string name) {
			var arg = string_param_name(name);
			var glue = "Ui.WebView." + name;
			sb.append_printf(
				"""	public bool %s(string %s) {
		return attached && %s(%s);
	}

""",
				name,
				arg,
				glue,
				arg
			);
		}

		static void emit_catalog_properties(
			GLib.StringBuilder sb,
			WebView2MethodCatalog catalog,
			WebView2HostOverrides overrides
		) {
			var props = new Gee.HashMap<string, ErgoProperty> ();
			foreach (var entry in catalog.entries) {
				if (overrides.is_ergo_skipped(entry.glue_name)) {
					continue;
				}
				switch (entry.glue_kind) {
				case WebView2GlueKind.WEBVIEW_GET_COM_STRING:
				case WebView2GlueKind.WEBVIEW_GET_BOOL:
				case WebView2GlueKind.WEBVIEW_GET_DOUBLE:
					add_property_get(props, entry, overrides);
					break;
				case WebView2GlueKind.WEBVIEW_PUT_BOOL:
				case WebView2GlueKind.WEBVIEW_PUT_DOUBLE:
					add_property_put(props, entry, overrides);
					break;
				default:
					break;
				}
			}
			var names = new Gee.ArrayList<string> ();
			foreach (var key in props.keys) {
				names.add(key);
			}
			names.sort((a, b) => a.collate(b));
			foreach (var name in names) {
				emit_property(sb, props[name]);
			}
		}

		static void add_property_get(
			Gee.HashMap<string, ErgoProperty> props,
			WebView2CatalogEntry entry,
			WebView2HostOverrides overrides
		) {
			var name = overrides.ergo_property_name(entry.glue_name);
			if (!props.has_key(name)) {
				props[name] = new ErgoProperty() { name = name };
			}
			props[name].get_glue = entry.glue_name;
			props[name].get_kind = entry.glue_kind;
		}

		static void add_property_put(
			Gee.HashMap<string, ErgoProperty> props,
			WebView2CatalogEntry entry,
			WebView2HostOverrides overrides
		) {
			var name = overrides.ergo_property_name(entry.glue_name);
			if (!props.has_key(name)) {
				props[name] = new ErgoProperty() { name = name };
			}
			props[name].put_glue = entry.glue_name;
		}

		static void emit_property(GLib.StringBuilder sb, ErgoProperty prop) {
			if (prop.get_glue == null) {
				return;
			}
			var get_call = "Ui.WebView." + prop.get_glue;
			if (prop.put_glue != null) {
				var put_call = "Ui.WebView." + prop.put_glue;
				if (prop.get_kind == WebView2GlueKind.WEBVIEW_GET_DOUBLE) {
					sb.append_printf(
						"""	public double %s {
		get { return attached ? %s() : 1.0; }
		set {
			if (attached) {
				%s(value);
			}
		}
	}

""",
						prop.name,
						get_call,
						put_call
					);
				} else {
					sb.append_printf(
						"""	public bool %s {
		get { return attached && %s(); }
		set {
			if (attached) {
				%s(value);
			}
		}
	}

""",
						prop.name,
						get_call,
						put_call
					);
				}
				return;
			}
			switch (prop.get_kind) {
			case WebView2GlueKind.WEBVIEW_GET_COM_STRING:
				sb.append_printf(
					"""	public string %s {
		owned get { return attached ? %s() : ""; }
	}

""",
					prop.name,
					get_call
				);
				break;
			case WebView2GlueKind.WEBVIEW_GET_BOOL:
				sb.append_printf(
					"""	public bool %s {
		get { return attached && %s(); }
	}

""",
					prop.name,
					get_call
				);
				break;
			case WebView2GlueKind.WEBVIEW_GET_DOUBLE:
				sb.append_printf(
					"""	public double %s {
		get { return attached ? %s() : 1.0; }
	}

""",
					prop.name,
					get_call
				);
				break;
			default:
				break;
			}
		}

		static void emit_private_helpers(GLib.StringBuilder sb) {
			sb.append("""
	void push_layout() {
		if (!attached || width <= 0 || height <= 0) {
			return;
		}
		Ui.WebView.set_bounds_xywh(x, y, width, height);
	}

	void on_parent_resized(uint parent_width, uint parent_height) {
		if (!resize_with_parent) {
			return;
		}
		set_bounds(0, 0, (int) parent_width, (int) parent_height);
	}

	void on_parent_destroyed() {
		if (attached) {
			Ui.WebView.destroy();
			attached = false;
		}
	}

""");
		}

		static string emit_signal(string ergo) {
			var trimmed = ergo.strip();
			if (!trimmed.contains("(")) {
				return "	public signal void %s;\n\n".printf(trimmed);
			}
			var open = trimmed.index_of("(");
			var name = trimmed.substring(0, open);
			if (trimmed.contains("cancellable")) {
				return "	public signal void %s();\n\n".printf(name);
			}
			var close = trimmed.last_index_of(")");
			var params = trimmed.substring(open, close - open + 1);
			return "	public signal void %s%s;\n\n".printf(name, params);
		}

		static string string_param_name(string glue_method) {
			switch (glue_method) {
			case "navigate":
				return "url";
			case "navigate_to_string":
				return "html";
			case "post_web_message_as_json":
				return "json";
			case "post_web_message_as_string":
				return "text";
			case "execute_script":
				return "js";
			default:
				return "text";
			}
		}
	}
}
