/*
 * Emit Win32 GetLastError → Vala errordomain helpers(Phase 4d).
 */

namespace Generate {
	public class ErrorEmitter : Object {
		const string GENERATED_HEADER = """/* Generated by generate-binding — do not edit. */

""";

		public string emit() {
			return @"$(GENERATED_HEADER)using Win32.System;

namespace Win32 {

	/** Returns false and sets err from GetLastError when ok == 0. */
	public bool win32_bool_ok(int ok, out uint err) {
		if (ok != 0) {
			err = 0;
			return true;
		}
		err = get_last_error();
		return false;
	}

	/** Returns false and sets err from GetLastError when p == null. */
	public bool win32_pointer_ok(void* p, out uint err) {
		if (p != null) {
			err = 0;
			return true;
		}
		err = get_last_error();
		return false;
	}
}
";
		}
	}
}