/*
 * Emit per-shard vapi from loaded ApiFile models.
 */

namespace Generate {
	public class VapiEmitter : Object {
		SymbolFilter filter;
		GLib.StringBuilder buffer;
		private Gee.HashSet<string> emitted_vala_names = new Gee.HashSet<string> ();
		private string shard_basename = "";

		public VapiEmitter (SymbolFilter filter) {
			this.filter = filter;
			this.buffer = new GLib.StringBuilder ();
		}

		bool claim_vala_name (string vala_name) {
			if (this.emitted_vala_names.contains (vala_name)) {
				return false;
			}
			this.emitted_vala_names.add (vala_name);
			return true;
		}

		void reset_shard () {
			this.buffer = new GLib.StringBuilder ();
			this.emitted_vala_names.clear ();
			this.shard_basename = "";
		}

		/** WC_* wide class strings — Vala literals in a CCode-free namespace (see win32-ui-control-strings.vapi). */
		public string emit_control_class_strings (Parse.ApiFileEntry entry) {
			this.reset_shard ();
			var ns = NameMapper.vala_namespace_from_basename (entry.basename);
			this.buffer.append ("/* Generated by generate-binding — do not edit. */\n\n");
			this.buffer.append_printf ("namespace %s {\n", ns);
			var basename = entry.basename;
			foreach (var c in entry.document.Constants) {
				if (NameMapper.skip_ansi_name (c.Name)) {
					continue;
				}
				if (!c.Name.has_prefix ("WC_")) {
					continue;
				}
				if (!VapiEmitter.is_string_constant (c)) {
					continue;
				}
				var full = Parse.ApiFile.full_name (basename, c.Name);
				if (!this.filter.include_symbol (full)) {
					continue;
				}
				var vala_name = NameMapper.to_constant_name (c.Name);
				if (!this.claim_vala_name (vala_name)) {
					continue;
				}
				this.emit_string_constant (c, vala_name);
			}
			this.buffer.append ("}\n");
			return this.buffer.str;
		}

		/** One vapi shard: namespace Win32.Ui.* { … } */
		public string emit_shard (Parse.ApiFileEntry entry) {
			this.reset_shard ();
			var ns = NameMapper.vala_namespace_from_basename (entry.basename);
			this.buffer.append ("/* Generated by generate-binding — do not edit. */\n\n");
			this.buffer.append ("[CCode (cprefix = \"\", cheader_filename = \"windows.h\")]\n");
			this.buffer.append_printf ("namespace %s {\n", ns);
			this.emit_shard_body (entry);
			if (entry.basename == "UI.WindowsAndMessaging.json") {
				this.emit_word_helpers ();
			}
			this.buffer.append ("}\n");
			return this.buffer.str;
		}

		/** Phase 1 monolith (deprecated for apps). */
		public string emit_all (Generate.Parse.ApiFileEntry[] files) {
			this.reset_shard ();
			this.buffer.append ("/* Generated by generate-binding — do not edit. */\n\n");
			this.buffer.append ("[CCode (cprefix = \"\", cheader_filename = \"windows.h\")]\n");
			this.buffer.append ("namespace Win32 {\n");
			foreach (var entry in files) {
				this.emit_shard_body (entry);
			}
			this.buffer.append ("}\n");
			return this.buffer.str;
		}

		public Gee.HashMap<string, string> emit_all_shards (Generate.Parse.ApiFileEntry[] files) {
			var map = new Gee.HashMap<string, string> ();
			foreach (var entry in files) {
				var pkg_id = NameMapper.json_basename_to_pkg_id (entry.basename);
				map[pkg_id] = this.emit_shard (entry);
			}
			return map;
		}

		void emit_shard_body (Parse.ApiFileEntry entry) {
			this.shard_basename = entry.basename;
			var basename = entry.basename;
			var doc = entry.document;

			foreach (var c in doc.Constants) {
				if (NameMapper.skip_ansi_name (c.Name)) {
					continue;
				}
				var full = Parse.ApiFile.full_name (basename, c.Name);
				if (!this.filter.include_symbol (full)) {
					continue;
				}
				this.emit_constant (c);
			}

			foreach (var t in doc.Types) {
				if (NameMapper.skip_ansi_name (t.Name)) {
					continue;
				}
				var full = Parse.ApiFile.full_name (basename, t.Name);
				if (!this.filter.include_symbol (full)) {
					continue;
				}
				if (t.Kind == "Enum") {
					this.emit_enum (t);
				}
			}

			foreach (var t in doc.Types) {
				if (NameMapper.skip_ansi_name (t.Name)) {
					continue;
				}
				var full = Parse.ApiFile.full_name (basename, t.Name);
				if (!this.filter.include_symbol (full)) {
					continue;
				}
				if (t.Kind == "FunctionPointer") {
					this.emit_delegate (t);
				}
			}

			foreach (var t in doc.Types) {
				if (NameMapper.skip_ansi_name (t.Name)) {
					continue;
				}
				var full = Parse.ApiFile.full_name (basename, t.Name);
				if (!this.filter.include_symbol (full)) {
					continue;
				}
				if (t.Kind == "Struct") {
					this.emit_struct (t);
				}
			}

			foreach (var f in doc.Functions) {
				if (NameMapper.skip_ansi_name (f.Name)) {
					continue;
				}
				var full = Parse.ApiFile.full_name (basename, f.Name);
				if (!this.filter.include_symbol (full)) {
					continue;
				}
				this.emit_function (f);
			}
		}

		void emit_constant (Parse.Constant c) {
			var vala_name = NameMapper.to_constant_name (c.Name);
			if (!this.claim_vala_name (vala_name)) {
				return;
			}
			if (VapiEmitter.is_string_constant (c)) {
				return;
			}
			var vala_type = VapiEmitter.vala_type_for (c.Type, c.ValueType);
			if (!VapiEmitter.is_valid_const_vala_type (vala_type)) {
				return;
			}
			this.buffer.append_printf (
				"\t[CCode (cname = \"%s\")]\n\tpublic const %s %s;\n\n",
				c.Name,
				vala_type,
				vala_name
			);
		}

		void emit_string_constant (Parse.Constant c, string vala_name) {
			if (c.ValueText.length == 0) {
				return;
			}
			this.buffer.append_printf ("\tpublic const uint16[] %s = {\n", vala_name);
			for (int i = 0; i < c.ValueText.length; i++) {
				this.buffer.append_printf ("\t\t'%c', ", c.ValueText[i]);
			}
			this.buffer.append ("0\n\t};\n\n");
		}

		void emit_word_helpers () {
			this.buffer.append ("\t[CCode (cheader_filename = \"\")]\n");
			this.buffer.append ("\tpublic static uint loword (ulong l) {\n");
			this.buffer.append ("\t\treturn (uint) (l & 0xffff);\n");
			this.buffer.append ("\t}\n\n");
			this.buffer.append ("\tpublic static uint hiword (ulong l) {\n");
			this.buffer.append ("\t\treturn (uint) ((l >> 16) & 0xffff);\n");
			this.buffer.append ("\t}\n\n");
		}

		static bool is_string_constant (Parse.Constant c) {
			if (c.ValueType == "String") {
				return true;
			}
			if (c.Type.Kind == "Native" && c.Type.Name == "String") {
				return true;
			}
			return false;
		}

		void emit_enum (Parse.MetadataType t) {
			if (t.Values.size == 0) {
				return;
			}
			var vala_name = NameMapper.to_vala_type (t.Name);
			if (!this.claim_vala_name (vala_name)) {
				return;
			}
			if (t.Flags) {
				this.buffer.append ("\t[Flags]\n");
			}
			this.buffer.append_printf (
				"\t[CCode (cname = \"%s\", has_type_id = false)]\n",
				VapiEmitter.enum_c_type_id (t.IntegerBase)
			);
			this.buffer.append_printf ("\tpublic enum %s {\n", vala_name);
			var members = new Gee.HashSet<string> ();
			foreach (var v in t.Values) {
				if (NameMapper.skip_ansi_name (v.Name)) {
					continue;
				}
				if (members.contains (v.Name)) {
					continue;
				}
				members.add (v.Name);
				this.buffer.append_printf ("\t\t[CCode (cname = \"%s\")]\n", v.Name);
				this.buffer.append_printf ("\t\t%s = %s,\n", v.Name, VapiEmitter.format_enum_value (v.Value));
			}
			this.buffer.append ("\t}\n\n");
		}

		static string enum_c_type_id (string integer_base) {
			switch (integer_base) {
			case "Int32":
				return "INT";
			case "UInt16":
				return "UINT16";
			case "UInt64":
				return "UINT64";
			default:
				return "UINT";
			}
		}

		static string format_enum_value (int64 value) {
			if (value < 0) {
				return value.to_string ();
			}
			if (value > 0xFFFF) {
				return "0x%08llx".printf ((ulong) value);
			}
			return value.to_string ();
		}

		void emit_struct (Parse.MetadataType t) {
			if (NameMapper.skip_ansi_variant_name (t.Name)) {
				return;
			}
			var vala_name = NameMapper.to_vala_type (t.Name);
			if (!this.claim_vala_name (vala_name)) {
				return;
			}
			this.buffer.append_printf ("\t[CCode (cname = \"%s\")]\n", t.Name);
			this.buffer.append_printf ("\tpublic struct %s {\n", vala_name);
			foreach (var field in t.Fields) {
				if (t.Name == "MSG" && field.Name == "pt") {
					this.buffer.append ("\t\tpublic int pt_x;\n");
					this.buffer.append ("\t\tpublic int pt_y;\n");
					continue;
				}
				var ftype = VapiEmitter.vala_type_for_field (field.Type, this.shard_basename);
				this.buffer.append_printf ("\t\tpublic %s %s;\n", ftype, field.Name);
			}
			this.buffer.append ("\t}\n\n");
		}

		void emit_delegate (Parse.MetadataType t) {
			var vala_name = NameMapper.to_vala_type (t.Name);
			if (!this.claim_vala_name (vala_name)) {
				return;
			}
			this.buffer.append_printf ("\t[CCode (cname = \"%s\", has_target = false)]\n", t.Name);
			this.buffer.append_printf ("\tpublic delegate %s %s (\n",
				VapiEmitter.vala_type_for (t.ReturnType, ""),
				vala_name
			);
			var n = t.Params.size;
			for (int i = 0; i < n; i++) {
				var p = t.Params.get (i);
				var ptype = VapiEmitter.vala_param_type (p);
				var comma = i < n - 1 ? "," : "";
				this.buffer.append_printf (
					"\t\t%s %s%s\n",
					ptype,
					NameMapper.delegate_param_name (t.Name, p.Name, i),
					comma
				);
			}
			this.buffer.append ("\t);\n\n");
		}

		void emit_function (Parse.Function f) {
			var vala_name = NameMapper.to_snake_function (f.Name);
			if (!this.claim_vala_name (vala_name)) {
				return;
			}
			var ret = VapiEmitter.vala_type_for (f.ReturnType, "");
			this.buffer.append_printf ("\t[CCode (cname = \"%s\")]\n", f.Name);
			this.buffer.append_printf ("\tpublic extern %s %s (\n", ret, vala_name);
			var n = f.Params.size;
			for (int i = 0; i < n; i++) {
				var p = f.Params.get (i);
				var ptype = VapiEmitter.vala_param_type (p);
				var pname = VapiEmitter.param_vala_name (f.Name, p);
				var comma = i < n - 1 ? "," : "";
				this.buffer.append_printf ("\t\t%s %s%s\n", ptype, pname, comma);
			}
			this.buffer.append ("\t);\n\n");
		}

		static string param_vala_name (string function_c_name, Parse.Parameter p) {
			if (p.Name == "param0" && function_c_name.has_prefix ("RegisterClassEx")) {
				return "lp_wcx";
			}
			return NameMapper.to_snake (p.Name);
		}

		public static bool is_valid_const_vala_type (string vala_type) {
			if (vala_type == "void*") {
				return false;
			}
			return vala_type.index_of_char ('*') < 0;
		}

		static string qualified_api_type (Parse.TypeRef type_ref, string shard_basename) {
			var type_name = type_ref.TargetKind == "FunctionPointer"
				? NameMapper.to_vala_type (type_ref.Name)
				: VapiEmitter.map_type_name (type_ref.Name);
			if (type_ref.Api == "" || shard_basename == "") {
				return type_name;
			}
			var ref_basename = type_ref.Api + ".json";
			if (ref_basename == shard_basename) {
				return type_name;
			}
			var ns = NameMapper.vala_namespace_from_basename (ref_basename);
			return ns + "." + type_name;
		}

		public static string vala_type_for (Parse.TypeRef type_ref, string value_type_fallback) {
			return VapiEmitter.vala_type_for_ref (type_ref, value_type_fallback, null);
		}

		public static string vala_type_for_field (Parse.TypeRef type_ref, string shard_basename = "") {
			var base_type = VapiEmitter.vala_type_for_ref (type_ref, "", null, shard_basename);
			if (VapiEmitter.is_wide_string_vala_type (type_ref, base_type)) {
				return "unowned " + base_type;
			}
			return base_type;
		}

		public static string vala_param_type (Parse.Parameter p) {
			var base_type = VapiEmitter.vala_type_for_ref (p.Type, "", p.Attrs);
			var tid = VapiEmitter.type_id_for (p.Type.Name);
			if (tid == null && p.Type.Child != null) {
				tid = VapiEmitter.type_id_for (p.Type.Child.Name);
			}
			if (tid == null) {
				return base_type;
			}
			// unowned on extern In wide-string params is already Vala's default — explicit unowned warns.
			return "[CCode (type_id = \"%s\")] ".printf (tid) + base_type;
		}

		static bool is_wide_string_vala_type (Parse.TypeRef type_ref, string base_type) {
			if (base_type != "uint16*") {
				return false;
			}
			if (type_ref.Kind == "ApiRef") {
				return VapiEmitter.type_id_for (type_ref.Name) == "LPCWSTR";
			}
			if (type_ref.Kind == "PointerTo" && type_ref.Child != null) {
				return type_ref.Child.Name == "UInt16" || type_ref.Child.Name == "WCHAR";
			}
			return false;
		}

		static string vala_type_for_ref (
			Parse.TypeRef type_ref,
			string value_type_fallback,
			Gee.ArrayList<string>? attrs,
			string shard_basename = ""
		) {
			if (type_ref.Kind == "PointerTo" && type_ref.Child != null) {
				var inner = VapiEmitter.vala_type_for_ref (type_ref.Child, "", null, shard_basename);
				if (attrs != null && VapiEmitter.attrs_contain (attrs, "Out")) {
					return "out " + inner;
				}
				if (attrs != null && VapiEmitter.attrs_contain (attrs, "In")) {
					if (inner == "void*" || inner.has_suffix ("*")) {
						return inner;
					}
					return "ref " + inner;
				}
				return inner + "*";
			}

			if (type_ref.Kind == "ApiRef") {
				if (NameMapper.skip_ansi_name (type_ref.Name)) {
					return "void*";
				}
				if (type_ref.TargetKind == "FunctionPointer") {
					return VapiEmitter.qualified_api_type (type_ref, shard_basename);
				}
				return VapiEmitter.map_type_name (type_ref.Name);
			}

			if (type_ref.Name != "") {
				return VapiEmitter.map_type_name (type_ref.Name);
			}
			if (value_type_fallback != "") {
				return VapiEmitter.map_type_name (value_type_fallback);
			}
			if (type_ref.Kind == "Native" && type_ref.Name == "Void") {
				return "void*";
			}
			return "void*";
		}

		static bool attrs_contain (Gee.ArrayList<string> attrs, string needle) {
			foreach (var a in attrs) {
				if (a == needle) {
					return true;
				}
			}
			return false;
		}

		static string? type_id_for (string name) {
			switch (name) {
			case "HWND":
			case "HINSTANCE":
			case "HICON":
			case "HCURSOR":
			case "HBRUSH":
			case "HMENU":
				return name;
			case "LPCWSTR":
			case "LPWSTR":
			case "PWSTR":
				return "LPCWSTR";
			default:
				return null;
			}
		}

		static string map_type_name (string name) {
			switch (name) {
			case "UInt32":
			case "uint":
				return "uint";
			case "Int32":
				return "int";
			case "UInt64":
				return "ulong";
			case "Int64":
				return "long";
			case "UInt16":
			case "WORD":
				return "ushort";
			case "BOOL":
				return "int";
			case "HWND":
			case "HINSTANCE":
			case "HICON":
			case "HCURSOR":
			case "HBRUSH":
			case "HMENU":
			case "HANDLE":
				return "void*";
			case "LPCWSTR":
			case "LPWSTR":
			case "PWSTR":
				return "uint16*";
			case "LRESULT":
				return "long";
			case "WPARAM":
				return "ulong";
			case "LPARAM":
				return "long";
			case "ATOM":
				return "ushort";
			case "MSG":
				return "Msg";
			case "WNDCLASSEX":
			case "WNDCLASSEXW":
				return "WndClassEx";
			case "WNDPROC":
				return "WndProc";
			default:
				if (name.has_suffix ("_STYLE") || name.has_suffix ("_STYLES")) {
					return "uint";
				}
				if (name.has_prefix ("WINDOW_") || name.has_prefix ("WNDCLASS_")) {
					return "uint";
				}
				return "void*";
			}
		}
	}
}
