/*
 * Emit vapi/win32-ui.vapi from loaded ApiFile models.
 */

namespace Generate {
	public class VapiEmitter : Object {
		SymbolFilter filter;
		GLib.StringBuilder buffer;
		private Gee.HashSet<string> emitted_vala_names = new Gee.HashSet<string> ();

		public VapiEmitter (SymbolFilter filter) {
			this.filter = filter;
			this.buffer = new GLib.StringBuilder ();
		}

		/** First emission wins; later JSON blobs often repeat the same Win32 name. */
		bool claim_vala_name (string vala_name) {
			if (this.emitted_vala_names.contains (vala_name)) {
				return false;
			}
			this.emitted_vala_names.add (vala_name);
			return true;
		}

		public string emit_all (Gee.ArrayList<Parse.ApiFileEntry> files) {
			this.buffer.append ("/* Generated by generate-binding — do not edit. */\n\n");
			this.buffer.append ("[CCode (cprefix = \"\", cheader_filename = \"windows.h\")]\n");
			this.buffer.append ("namespace Win32 {\n");

			foreach (var entry in files) {
				this.emit_file (entry);
			}

			this.buffer.append ("}\n");
			return this.buffer.str;
		}

		void emit_file (Parse.ApiFileEntry entry) {
			var basename = entry.basename;
			var doc = entry.document;

			foreach (var c in doc.Constants) {
				var full = Parse.ApiFile.full_name (basename, c.Name);
				if (!this.filter.include_symbol (full)) {
					continue;
				}
				this.emit_constant (c);
			}

			foreach (var t in doc.Types) {
				var full = Parse.ApiFile.full_name (basename, t.Name);
				if (!this.filter.include_symbol (full)) {
					continue;
				}
				if (t.Kind == "Struct") {
					this.emit_struct (t);
				} else if (t.Kind == "FunctionPointer") {
					this.emit_delegate (t);
				}
			}

			foreach (var f in doc.Functions) {
				var full = Parse.ApiFile.full_name (basename, f.Name);
				if (!this.filter.include_symbol (full)) {
					continue;
				}
				this.emit_function (f);
			}
		}

		void emit_constant (Parse.Constant c) {
			var vala_name = NameMapper.to_constant_name (c.Name);
			if (!this.claim_vala_name (vala_name)) {
				return;
			}
			var vala_type = VapiEmitter.vala_type_for (c.Type, c.ValueType);
			if (!VapiEmitter.is_valid_const_vala_type (vala_type)) {
				return;
			}
			this.buffer.append_printf (
				"\t[CCode (cname = \"%s\")]\n\tpublic const %s %s;\n\n",
				c.Name,
				vala_type,
				vala_name
			);
		}

		void emit_struct (Parse.MetadataType t) {
			var vala_name = NameMapper.to_vala_type (t.Name);
			if (!this.claim_vala_name (vala_name)) {
				return;
			}
			this.buffer.append_printf ("\t[CCode (cname = \"%s\")]\n", t.Name);
			this.buffer.append_printf ("\tpublic struct %s {\n", vala_name);
			foreach (var field in t.Fields) {
				if (t.Name == "MSG" && field.Name == "pt") {
					this.buffer.append ("\t\tpublic int pt_x;\n");
					this.buffer.append ("\t\tpublic int pt_y;\n");
					continue;
				}
				var ftype = VapiEmitter.vala_type_for (field.Type, "");
				this.buffer.append_printf ("\t\tpublic %s %s;\n", ftype, field.Name);
			}
			this.buffer.append ("\t}\n\n");
		}

		void emit_delegate (Parse.MetadataType t) {
			var vala_name = NameMapper.to_vala_type (t.Name);
			if (!this.claim_vala_name (vala_name)) {
				return;
			}
			this.buffer.append_printf ("\t[CCode (cname = \"%s\", has_target = false)]\n", t.Name);
			this.buffer.append_printf ("\tpublic delegate %s %s (\n",
				VapiEmitter.vala_type_for (t.ReturnType, ""),
				vala_name
			);
			var n = t.Params.size;
			for (int i = 0; i < n; i++) {
				var p = t.Params.get (i);
				var ptype = VapiEmitter.vala_param_type (p.Type);
				var comma = i < n - 1 ? "," : "";
				this.buffer.append_printf ("\t\t%s %s%s\n", ptype, NameMapper.to_snake (p.Name), comma);
			}
			this.buffer.append ("\t);\n\n");
		}

		void emit_function (Parse.Function f) {
			var vala_name = NameMapper.to_snake_function (f.Name);
			if (!this.claim_vala_name (vala_name)) {
				return;
			}
			var ret = VapiEmitter.vala_type_for (f.ReturnType, "");
			this.buffer.append_printf ("\t[CCode (cname = \"%s\")]\n", f.Name);
			this.buffer.append_printf ("\tpublic extern %s %s (\n", ret, vala_name);
			var n = f.Params.size;
			for (int i = 0; i < n; i++) {
				var p = f.Params.get (i);
				var ptype = VapiEmitter.vala_param_type (p.Type);
				var comma = i < n - 1 ? "," : "";
				this.buffer.append_printf ("\t\t%s %s%s\n", ptype, NameMapper.to_snake (p.Name), comma);
			}
			this.buffer.append ("\t);\n\n");
		}

		/** Vala allows only scalar const types in vapi (no pointers). */
		public static bool is_valid_const_vala_type (string vala_type) {
			if (vala_type == "void*") {
				return false;
			}
			return vala_type.index_of_char ('*') < 0;
		}

		public static string vala_type_for (Parse.TypeRef type_ref, string value_type_fallback) {
			if (type_ref.Name != "") {
				return VapiEmitter.map_type_name (type_ref.Name);
			}
			if (value_type_fallback != "") {
				return VapiEmitter.map_type_name (value_type_fallback);
			}
			return "void*";
		}

		public static string vala_param_type (Parse.TypeRef type_ref) {
			var base_type = VapiEmitter.vala_type_for (type_ref, "");
			var tid = VapiEmitter.type_id_for (type_ref.Name);
			if (tid == null) {
				return base_type;
			}
			return "[CCode (type_id = \"%s\")] ".printf (tid) + base_type;
		}

		static string? type_id_for (string name) {
			switch (name) {
			case "HWND":
			case "HINSTANCE":
			case "HICON":
			case "HCURSOR":
			case "HBRUSH":
			case "HMENU":
				return name;
			case "LPCWSTR":
			case "LPWSTR":
			case "PWSTR":
				return "LPCWSTR";
			default:
				return null;
			}
		}

		static string map_type_name (string name) {
			switch (name) {
			case "UInt32":
			case "uint":
				return "uint";
			case "Int32":
				return "int";
			case "UInt64":
				return "ulong";
			case "Int64":
				return "long";
			case "UInt16":
			case "WORD":
				return "ushort";
			case "BOOL":
				return "int";
			case "HWND":
			case "HINSTANCE":
			case "HICON":
			case "HCURSOR":
			case "HBRUSH":
			case "HMENU":
			case "HANDLE":
				return "void*";
			case "LPCWSTR":
			case "LPWSTR":
			case "PWSTR":
				return "uint16*";
			case "LRESULT":
				return "long";
			case "WPARAM":
				return "ulong";
			case "LPARAM":
				return "long";
			case "ATOM":
				return "ushort";
			default:
				return "void*";
			}
		}
	}
}
