/*
 * Emit C COBJMACROS wrappers + Vala extern declarations for WebView2 sync COM calls.
 * Specs come from WebView2MethodCatalog (WebView2.json + filter + overrides).
 */

namespace Generate {
	public class WebView2ComSyncEmitter : Object {
		public class SyncMethod : Object {
			public string glue_name { get; set; default = ""; }
			public string c_name { get; set; default = ""; }
			public string vala_call { get; set; default = ""; }
			public string com_call { get; set; default = ""; }
			public string c_sig { get; set; default = ""; }
			public string vala_sig { get; set; default = ""; }
		}

		Gee.ArrayList<SyncMethod> methods = new Gee.ArrayList<SyncMethod> ();

		const string C_HEADER = """/* Generated by generate-binding — do not edit. */

#define COBJMACROS
#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#include "win32-ui-webview2-com-sync.h"
#include "win32-ui-webview2-sdk.h"

""";

		const string H_HEADER = """/* Generated by generate-binding — do not edit. */
#ifndef VALA_WIN32_UI_WEBVIEW2_COM_SYNC_H
#define VALA_WIN32_UI_WEBVIEW2_COM_SYNC_H

#include "win32-ui-webview2-sdk.h"

#ifdef __cplusplus
extern "C" {
#endif

""";

		const string H_FOOTER = """
#ifdef __cplusplus
}
#endif

#endif /* VALA_WIN32_UI_WEBVIEW2_COM_SYNC_H */
""";

		const string VALA_HEADER = """/* Generated by generate-binding — do not edit. */

using Microsoft.Web.WebView2.Win32;

namespace Win32.Ui.WebView {

""";

		const string VALA_FOOTER = """
}

""";

		public void load_from_catalog(WebView2MethodCatalog catalog) {
			methods.clear();
			var seen = new Gee.HashSet<string> ();
			foreach (var entry in catalog.entries) {
				if (!entry.emit_com_sync || seen.contains(entry.glue_name)) {
					continue;
				}
				var method = build_method(entry);
				if (method != null) {
					seen.add(entry.glue_name);
					methods.add(method);
				}
			}
		}

		public SyncMethod? method_for(string glue_name) {
			foreach (var m in methods) {
				if (m.glue_name == glue_name) {
					return m;
				}
			}
			return null;
		}

		public string emit_c() {
			var sb = new GLib.StringBuilder(C_HEADER);
			foreach (var m in methods) {
				sb.append_printf("%s\n{\n\treturn %s;\n}\n\n", m.c_sig, m.com_call);
			}
			return sb.str;
		}

		public string emit_h() {
			var sb = new GLib.StringBuilder(H_HEADER);
			foreach (var m in methods) {
				sb.append(m.c_sig);
				sb.append(";\n\n");
			}
			sb.append(H_FOOTER);
			return sb.str;
		}

		public string emit_vala_externs() {
			var sb = new GLib.StringBuilder(VALA_HEADER);
			foreach (var m in methods) {
				sb.append_printf(
					"""[CCode(cheader_filename = "win32-ui-webview2-com-sync.h", cname = "%s")]
extern %s;

""",
					m.c_name,
					m.vala_sig
				);
			}
			sb.append(VALA_FOOTER);
			return sb.str;
		}

		SyncMethod? build_method(WebView2CatalogEntry entry) {
			var com_method = entry.com_method;
			var glue_name = entry.glue_name;
			var iface_name = entry.iface_name;
			var method_name = entry.com_method_name;
			var host = entry.host;
			var host_short = host == "controller" ? "controller" : "webview";
			var host_iface = host == "controller" ? "ICoreWebView2Controller" : "ICoreWebView2";
			var host_param = host_short;
			var c_name = "vala_webview2_com_%s_%s".printf(host_short, glue_name);
			var extern_name = "com_%s_%s".printf(host_short, glue_name);
			var macro = "%s_%s".printf(iface_name, method_name);
			var c_params = new Gee.ArrayList<string> ();
			var c_args = new Gee.ArrayList<string> ();
			var vala_params = new Gee.ArrayList<string> ();
			var vala_args = new Gee.ArrayList<string> ();
			c_params.add("%s *%s".printf(host_iface, host_param));
			vala_params.add("%s %s".printf(host_iface, host_param));
			c_args.add(host_param);
			vala_args.add(host_param);
			bool getter = method_name.has_prefix("get_");
			foreach (var param in com_method.Params) {
				string c_param;
				string vala_param;
				string c_arg;
				string vala_arg;
				map_param(param, glue_name, getter, out c_param, out vala_param, out c_arg, out vala_arg);
				c_params.add(c_param);
				vala_params.add(vala_param);
				c_args.add(c_arg);
				vala_args.add(vala_arg);
			}
			var com_call = "%s (%s)".printf(macro, string.joinv(", ", c_args.to_array()));
			var c_sig = "HRESULT %s (%s)".printf(c_name, string.joinv(", ", c_params.to_array()));
			var vala_sig = "int %s (%s)".printf(extern_name, string.joinv(", ", vala_params.to_array()));
			string vala_call = entry.vala_call;
			if (vala_call == null || vala_call.length == 0) {
				vala_call = default_vala_call(glue_name, extern_name, host, vala_args.to_array());
			}
			return new SyncMethod() {
				glue_name = glue_name,
				c_name = c_name,
				vala_call = vala_call,
				com_call = com_call,
				c_sig = c_sig,
				vala_sig = vala_sig,
			};
		}

		static void map_param(
			Parse.Parameter param,
			string glue_name,
			bool getter,
			out string c_param,
			out string vala_param,
			out string c_arg,
			out string vala_arg
		) {
			var type_ref = param.Type;
			var pname = NameMapper.to_snake(param.Name.length > 0 ? param.Name : "param");
			if (getter && type_ref.Kind == "PointerTo") {
				if (type_ref.Child != null && type_ref.Child.Name == "LPWSTR") {
					c_param = "LPWSTR *%s".printf(pname);
					vala_param = "out uint16* %s".printf(pname);
					c_arg = pname;
					vala_arg = "out %s".printf(pname);
					return;
				}
				if (type_ref.Child != null && type_ref.Child.Kind == "ApiRef" && type_ref.Child.Name == "BOOL") {
					c_param = "BOOL *%s".printf(pname);
					vala_param = "out int %s".printf(pname);
					c_arg = pname;
					vala_arg = "out val";
					return;
				}
				if (type_ref.Child != null && is_floating_type(type_ref.Child.Name)) {
					c_param = "DOUBLE *%s".printf(pname);
					vala_param = "out double %s".printf(pname);
					c_arg = pname;
					vala_arg = "out val";
					return;
				}
			}
			if (type_ref.Kind == "ApiRef" && type_ref.Name == "RECT") {
				c_param = "const RECT *%s".printf(pname);
				vala_param = "Rect %s".printf(pname);
				c_arg = "*%s".printf(pname);
				vala_arg = "g_host.bounds";
				return;
			}
			if (type_ref.Kind == "ApiRef" && type_ref.Name == "BOOL") {
				c_param = "BOOL %s".printf(pname);
				vala_param = "int %s".printf(pname);
				c_arg = pname;
				vala_arg = "visible ? 1 : 0";
				return;
			}
			if (type_ref.Kind == "ApiRef" && is_floating_type(type_ref.Name)) {
				c_param = "DOUBLE %s".printf(pname);
				vala_param = "double %s".printf(pname);
				c_arg = pname;
				vala_arg = "zoom";
				return;
			}
			if (type_ref.Kind == "ApiRef" && type_ref.Name == "LPCWSTR") {
				c_param = "LPCWSTR %s".printf(pname);
				vala_param = "[CCode(type_id = \"LPCWSTR\")] uint16* %s".printf(pname);
				c_arg = pname;
				vala_arg = string_param_vala_arg(glue_name, pname);
				return;
			}
			if (type_ref.Kind == "PointerTo" && type_ref.Child != null && type_ref.Child.Name == "LPCWSTR") {
				c_param = "LPCWSTR %s".printf(pname);
				vala_param = "[CCode(type_id = \"LPCWSTR\")] uint16* %s".printf(pname);
				c_arg = pname;
				vala_arg = string_param_vala_arg(glue_name, pname);
				return;
			}
			c_param = "void* %s".printf(pname);
			vala_param = "void* %s".printf(pname);
			c_arg = pname;
			vala_arg = pname;
		}

		static bool is_floating_type(string name) {
			return name == "DOUBLE" || name == "double";
		}

		static string string_param_vala_arg(string glue_name, string c_name) {
			switch (glue_name) {
			case "navigate_to_string":
				return "WideString(html).ptr";
			case "post_web_message_as_json":
				return "WideString(json).ptr";
			case "post_web_message_as_string":
				return "WideString(text).ptr";
			case "navigate":
				return "g_host.pending_url.ptr";
			default:
				switch (c_name) {
				case "html_content":
					return "WideString(html).ptr";
				case "web_message_as_json":
					return "WideString(json).ptr";
				case "web_message_as_string":
					return "WideString(text).ptr";
				case "uri":
					return "g_host.pending_url.ptr";
				default:
					return c_name;
				}
			}
		}

		static string default_vala_call(
			string glue_name,
			string extern_name,
			string host,
			string[] vala_args
		) {
			if (glue_name == "put_bounds") {
				return "%s (host_controller_com(), g_host.bounds)".printf(extern_name);
			}
			var host_ref = host == "controller" ? "host_controller_com()" : "host_webview_com()";
			if (vala_args.length <= 1) {
				return "%s (%s)".printf(extern_name, host_ref);
			}
			var call_args = new Gee.ArrayList<string> ();
			call_args.add(host_ref);
			for (int i = 1; i < vala_args.length; i++) {
				call_args.add(vala_args[i]);
			}
			return "%s (%s)".printf(extern_name, string.joinv(", ", call_args.to_array()));
		}
	}
}
