/*
 * Emit Win32.Ui.WebView glue methods from profiles.WebView2.ergo_native_map.
 */

namespace Generate {
	public class WebView2GlueEmitter : Object {
		const string GENERATED_HEADER = """/* Generated by generate-binding — do not edit. */

namespace Win32.Ui.WebView {

""";

		const string GENERATED_FOOTER = """
}

""";

		enum EmitKind {
			SKIP,
			WEBVIEW_VOID,
			WEBVIEW_STRING,
			WEBVIEW_GET_COM_STRING,
			WEBVIEW_GET_BOOL,
			WEBVIEW_STUB,
			CONTROLLER_PUT_BOOL,
			CONTROLLER_GET_BOOL,
			CONTROLLER_PUT_DOUBLE,
			CONTROLLER_GET_DOUBLE,
		}

		public string emit (Parse.WidgetConventionsFile conventions) {
			Parse.WidgetBehaviorProfileSpec? profile;
			if (!conventions.profiles.has_key ("WebView2")) {
				return GENERATED_HEADER + GENERATED_FOOTER;
			}
			profile = conventions.profiles["WebView2"];
			var sb = new GLib.StringBuilder (GENERATED_HEADER);
			var seen = new Gee.HashSet<string> ();
			foreach (var entry in profile.ergo_native_map) {
				foreach (var name in glue_method_names (entry.glue)) {
					if (seen.contains (name)) {
						continue;
					}
					var kind = classify (name, entry);
					if (kind == EmitKind.SKIP) {
						continue;
					}
					seen.add (name);
					emit_method (sb, name, kind);
				}
			}
			sb.append (GENERATED_FOOTER);
			return sb.str;
		}

		static string[] glue_method_names (string glue) {
			var local = glue;
			var dot = local.last_index_of (".");
			if (dot >= 0) {
				local = local.substring (dot + 1);
			}
			local = local.strip ();
			if (local.contains (" / ")) {
				var parts = local.split (" / ");
				var names = new Gee.ArrayList<string> ();
				foreach (var part in parts) {
					names.add (part.strip ());
				}
				return names.to_array ();
			}
			if (local.contains ("/")) {
				var slash = local.index_of ("/");
				var left = local.substring (0, slash).strip ();
				var right = local.substring (slash + 1).strip ();
				if (right.has_prefix ("get_")) {
					var suffix = right.substring (4);
					if (left == "put") {
						return { "put_" + suffix, right };
					}
				}
			}
			return { local };
		}

		static EmitKind classify (string name, Parse.ErgoNativeMapEntry entry) {
			if (entry.kind == "lifecycle" || entry.kind == "layout" || entry.kind == "signal") {
				return EmitKind.SKIP;
			}
			if (name == "navigate") {
				return EmitKind.SKIP;
			}
			if (name == "execute_script") {
				return EmitKind.WEBVIEW_STUB;
			}
			switch (name) {
			case "reload":
			case "stop":
			case "go_back":
			case "go_forward":
				return EmitKind.WEBVIEW_VOID;
			case "navigate_to_string":
			case "post_web_message_as_json":
				return EmitKind.WEBVIEW_STRING;
			case "get_source":
			case "get_document_title":
				return EmitKind.WEBVIEW_GET_COM_STRING;
			case "get_can_go_back":
			case "get_can_go_forward":
				return EmitKind.WEBVIEW_GET_BOOL;
			case "put_is_visible":
				return EmitKind.CONTROLLER_PUT_BOOL;
			case "get_is_visible":
				return EmitKind.CONTROLLER_GET_BOOL;
			case "put_zoom_factor":
				return EmitKind.CONTROLLER_PUT_DOUBLE;
			case "get_zoom_factor":
				return EmitKind.CONTROLLER_GET_DOUBLE;
			default:
				return EmitKind.SKIP;
			}
		}

		static void emit_method (GLib.StringBuilder sb, string name, EmitKind kind) {
			var cname = "vala_webview2_host_" + name;
			switch (kind) {
			case EmitKind.WEBVIEW_VOID:
				sb.append_printf (
					"""[CCode (cname = "%s")]
public bool %s () {
	if (!webview_ready ()) {
		return false;
	}
	return com_ok (g_host.webview.%s ());
}

""",
					cname,
					name,
					name
				);
				break;
			case EmitKind.WEBVIEW_STRING:
				var arg = string_param_name (name);
				var vapi = name;
				sb.append_printf (
					"""[CCode (cname = "%s")]
public bool %s (string %s) {
	if (!webview_ready () || %s.length == 0) {
		return false;
	}
	return com_ok (g_host.webview.%s (WideString (%s).ptr));
}

""",
					cname,
					name,
					arg,
					arg,
					vapi,
					arg
				);
				break;
			case EmitKind.WEBVIEW_GET_COM_STRING:
				var out_var = com_string_out_name (name);
				sb.append_printf (
					"""[CCode (cname = "%s")]
public string %s () {
	if (!webview_ready ()) {
		return "";
	}
	uint16* %s = null;
	if (!com_ok (g_host.webview.%s (out %s))) {
		return "";
	}
	return take_com_string (%s);
}

""",
					cname,
					name,
					out_var,
					name,
					out_var,
					out_var
				);
				break;
			case EmitKind.WEBVIEW_GET_BOOL:
				sb.append_printf (
					"""[CCode (cname = "%s")]
public bool %s () {
	if (!webview_ready ()) {
		return false;
	}
	int val = 0;
	if (!com_ok (g_host.webview.%s (out val))) {
		return false;
	}
	return val != 0;
}

""",
					cname,
					name,
					name
				);
				break;
			case EmitKind.WEBVIEW_STUB:
				sb.append_printf (
					"""[CCode (cname = "%s")]
public bool %s (string js) {
	/* vapi needs ICoreWebView2ExecuteScriptCompletedHandler — wiring deferred. */
	if (!webview_ready () || js.length == 0) {
		return false;
	}
	return false;
}

""",
					cname,
					name
				);
				break;
			case EmitKind.CONTROLLER_PUT_BOOL:
				sb.append_printf (
					"""[CCode (cname = "%s")]
public bool %s (bool visible) {
	if (!controller_ready ()) {
		return false;
	}
	return com_ok (g_host.controller.%s (visible ? 1 : 0));
}

""",
					cname,
					name,
					name
				);
				break;
			case EmitKind.CONTROLLER_GET_BOOL:
				sb.append_printf (
					"""[CCode (cname = "%s")]
public bool %s () {
	if (!controller_ready ()) {
		return false;
	}
	int val = 0;
	if (!com_ok (g_host.controller.%s (out val))) {
		return false;
	}
	return val != 0;
}

""",
					cname,
					name,
					name
				);
				break;
			case EmitKind.CONTROLLER_PUT_DOUBLE:
				sb.append_printf (
					"""[CCode (cname = "%s")]
public bool %s (double zoom) {
	if (!controller_ready ()) {
		return false;
	}
	return com_ok (g_host.controller.%s (zoom));
}

""",
					cname,
					name,
					name
				);
				break;
			case EmitKind.CONTROLLER_GET_DOUBLE:
				sb.append_printf (
					"""[CCode (cname = "%s")]
public double %s () {
	if (!controller_ready ()) {
		return 1.0;
	}
	double val = 1.0;
	if (!com_ok (g_host.controller.%s (out val))) {
		return 1.0;
	}
	return val;
}

""",
					cname,
					name,
					name
				);
				break;
			default:
				break;
			}
		}

		static string string_param_name (string glue_method) {
			switch (glue_method) {
			case "navigate_to_string":
				return "html";
			case "post_web_message_as_json":
				return "json";
			default:
				return "text";
			}
		}

		static string com_string_out_name (string glue_method) {
			switch (glue_method) {
			case "get_source":
				return "uri";
			case "get_document_title":
				return "title";
			default:
				return "com_str";
			}
		}
	}
}
