/*
 * Emit C COBJMACROS wrappers + Vala extern declarations for WebView2 sync COM calls.
 * Specs come from profiles.WebView2.ergo_native_map sync_com + WebView2.json metadata.
 */

namespace Generate {
	public class WebView2ComSyncEmitter : Object {
		public class SyncMethod : Object {
			public string glue_name { get; set; default = ""; }
			public string c_name { get; set; default = ""; }
			public string vala_call { get; set; default = ""; }
			public string com_call { get; set; default = ""; }
			public string c_sig { get; set; default = ""; }
			public string vala_sig { get; set; default = ""; }
		}

		Gee.HashMap<string, Parse.MetadataType> com_types = new Gee.HashMap<string, Parse.MetadataType> ();
		Gee.ArrayList<SyncMethod> methods = new Gee.ArrayList<SyncMethod> ();

		const string C_HEADER = """/* Generated by generate-binding — do not edit. */

#define COBJMACROS
#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#include "win32-ui-webview2-com-sync.h"
#include "win32-ui-webview2-sdk.h"

""";

		const string H_HEADER = """/* Generated by generate-binding — do not edit. */
#ifndef VALA_WIN32_UI_WEBVIEW2_COM_SYNC_H
#define VALA_WIN32_UI_WEBVIEW2_COM_SYNC_H

#include "win32-ui-webview2-sdk.h"

#ifdef __cplusplus
extern "C" {
#endif

""";

		const string H_FOOTER = """
#ifdef __cplusplus
}
#endif

#endif /* VALA_WIN32_UI_WEBVIEW2_COM_SYNC_H */
""";

		const string VALA_HEADER = """/* Generated by generate-binding — do not edit. */

using Microsoft.Web.WebView2.Win32;

namespace Win32.Ui.WebView {

""";

		const string VALA_FOOTER = """
}

""";

		public void load_from_files(string conventions_path, string webview2_json_path) throws GLib.Error {
			load_com_types(webview2_json_path);
			methods.clear();
			var entries = load_ergo_entries(conventions_path);
			var seen = new Gee.HashSet<string> ();
			foreach (var entry in entries) {
				foreach (var spec in expand_sync_specs(entry)) {
					var glue = spec.glue;
					if (glue == null || glue.length == 0 || seen.contains(glue)) {
						continue;
					}
					var method = build_method(entry, spec, glue);
					if (method != null) {
						seen.add(glue);
						methods.add(method);
					}
				}
			}
		}

		public SyncMethod? method_for(string glue_name) {
			foreach (var m in methods) {
				if (m.glue_name == glue_name) {
					return m;
				}
			}
			return null;
		}

		public string emit_c() {
			var sb = new GLib.StringBuilder(C_HEADER);
			foreach (var m in methods) {
				sb.append_printf("%s\n{\n\treturn %s;\n}\n\n", m.c_sig, m.com_call);
			}
			return sb.str;
		}

		public string emit_h() {
			var sb = new GLib.StringBuilder(H_HEADER);
			foreach (var m in methods) {
				sb.append(m.c_sig);
				sb.append(";\n\n");
			}
			sb.append(H_FOOTER);
			return sb.str;
		}

		public string emit_vala_externs() {
			var sb = new GLib.StringBuilder(VALA_HEADER);
			foreach (var m in methods) {
				sb.append_printf(
					"""[CCode(cheader_filename = "win32-ui-webview2-com-sync.h", cname = "%s")]
extern %s;

""",
					m.c_name,
					m.vala_sig
				);
			}
			sb.append(VALA_FOOTER);
			return sb.str;
		}

		void load_com_types(string json_path) throws GLib.Error {
			com_types.clear();
			var parser = new Json.Parser();
			parser.load_from_file(json_path);
			var root = parser.get_root();
			if (root == null || root.get_node_type() != Json.NodeType.OBJECT) {
				throw new GLib.IOError.FAILED("WebView2.json root must be object");
			}
			var types_node = root.get_object().get_member("Types");
			if (types_node == null || types_node.get_node_type() != Json.NodeType.ARRAY) {
				return;
			}
			var arr = types_node.get_array();
			for (uint i = 0; i < arr.get_length(); i++) {
				var type = Json.gobject_deserialize(typeof (Parse.MetadataType), arr.get_element(i)) as Parse.MetadataType;
				if (type != null && type.Kind == "Com") {
					com_types[type.Name] = type;
				}
			}
		}

		static Gee.ArrayList<Parse.ErgoNativeMapEntry> load_ergo_entries(string conventions_path) throws GLib.Error {
			var parser = new Json.Parser();
			parser.load_from_file(conventions_path);
			var root = parser.get_root();
			if (root == null || root.get_node_type() != Json.NodeType.OBJECT) {
				throw new GLib.IOError.FAILED("conventions root must be object");
			}
			var profiles = root.get_object().get_object_member("profiles");
			if (profiles == null || !profiles.has_member("WebView2")) {
				return new Gee.ArrayList<Parse.ErgoNativeMapEntry> ();
			}
			var webview2 = profiles.get_object_member("WebView2");
			var map_node = webview2.get_member("ergo_native_map");
			var entries = new Gee.ArrayList<Parse.ErgoNativeMapEntry> ();
			if (map_node == null || map_node.get_node_type() != Json.NodeType.ARRAY) {
				return entries;
			}
			var arr = map_node.get_array();
			for (uint i = 0; i < arr.get_length(); i++) {
				var obj = arr.get_element(i);
				if (obj == null || obj.get_node_type() != Json.NodeType.OBJECT) {
					continue;
				}
				var entry = new Parse.ErgoNativeMapEntry();
				var o = obj.get_object();
				entry.kind = read_string_member(o, "kind");
				entry.ergo = read_string_member(o, "ergo");
				entry.glue = read_string_member(o, "glue");
				entry.com = read_string_member(o, "com");
				entry.status = read_string_member(o, "status");
				var sync_node = o.get_member("sync_com");
				if (sync_node == null) {
					sync_node = o.get_member("sync-com");
				}
				entry.sync_com = Parse.ErgoNativeMapEntry.deserialize_sync_com(sync_node);
				entries.add(entry);
			}
			return entries;
		}

		static string read_string_member(Json.Object obj, string name) {
			var node = obj.get_member(name);
			if (node != null && node.get_value_type() == typeof (string)) {
				return node.get_string();
			}
			return "";
		}

		Gee.ArrayList<Parse.SyncComSpec> expand_sync_specs(Parse.ErgoNativeMapEntry entry) {
			return specs_for_entry(entry);
		}

		SyncMethod? build_method(
			Parse.ErgoNativeMapEntry entry,
			Parse.SyncComSpec spec,
			string glue_name
		) {
			string com_ref = spec.com ?? entry.com;
			string iface_name;
			string method_name;
			if (!parse_com_ref(com_ref, out iface_name, out method_name, glue_name)) {
				return null;
			}
			if (!com_types.has_key(iface_name)) {
				stderr.printf("webview2 com sync: unknown interface %s for glue %s\n", iface_name, glue_name);
				return null;
			}
			var com_type = com_types[iface_name];
			Parse.Function? com_method = null;
			foreach (var method in com_type.Methods) {
				if (method.Name == method_name) {
					com_method = method;
					break;
				}
			}
			if (com_method == null) {
				stderr.printf(
					"webview2 com sync: %s.%s not found for glue %s\n",
					iface_name,
					method_name,
					glue_name
				);
				return null;
			}
			var host = spec.host;
			if (host == null || host.length == 0) {
				host = default_host(iface_name);
			}
			var host_short = host == "controller" ? "controller" : "webview";
			var host_iface = host == "controller" ? "ICoreWebView2Controller" : "ICoreWebView2";
			var host_param = host == "controller" ? "controller" : "webview";
			var c_name = "vala_webview2_com_%s_%s".printf(host_short, glue_name);
			var extern_name = "com_%s_%s".printf(host_short, glue_name);
			var macro = "%s_%s".printf(iface_name, method_name);
			var c_params = new Gee.ArrayList<string> ();
			var c_args = new Gee.ArrayList<string> ();
			var vala_params = new Gee.ArrayList<string> ();
			var vala_args = new Gee.ArrayList<string> ();
			c_params.add("%s *%s".printf(host_iface, host_param));
			vala_params.add("%s %s".printf(host_iface, host_param));
			c_args.add(host_param);
			vala_args.add(host_param);
			bool getter = method_name.has_prefix("get_");
			foreach (var param in com_method.Params) {
				string c_param;
				string vala_param;
				string c_arg;
				string vala_arg;
				map_param(param, getter, out c_param, out vala_param, out c_arg, out vala_arg);
				c_params.add(c_param);
				vala_params.add(vala_param);
				c_args.add(c_arg);
				vala_args.add(vala_arg);
			}
			var com_call = "%s (%s)".printf(macro, string.joinv(", ", c_args.to_array()));
			var c_sig = "HRESULT %s (%s)".printf(c_name, string.joinv(", ", c_params.to_array()));
			var vala_sig = "int %s (%s)".printf(extern_name, string.joinv(", ", vala_params.to_array()));
			string vala_call = spec.vala_call;
			if (vala_call == null || vala_call.length == 0) {
				vala_call = default_vala_call(glue_name, extern_name, host, vala_args.to_array());
			}
			return new SyncMethod() {
				glue_name = glue_name,
				c_name = c_name,
				vala_call = vala_call,
				com_call = com_call,
				c_sig = c_sig,
				vala_sig = vala_sig,
			};
		}

		static bool parse_com_ref(
			string com_ref,
			out string iface_name,
			out string method_name,
			string glue_name
		) {
			iface_name = "";
			method_name = "";
			var dot = com_ref.last_index_of(".");
			if (dot < 0) {
				return false;
			}
			iface_name = com_ref.substring(0, dot).strip();
			var method_part = com_ref.substring(dot + 1).strip();
			if (method_part.contains("/")) {
				var slash = method_part.index_of("/");
				var left = method_part.substring(0, slash).strip();
				var right = method_part.substring(slash + 1).strip();
				if (glue_name.has_prefix("put_")) {
					method_name = left + "_" + right.substring(right.index_of("_") + 1);
				} else if (glue_name.has_prefix("get_")) {
					method_name = right;
				} else {
					method_name = right;
				}
			} else {
				method_name = method_part;
			}
			return iface_name.length > 0 && method_name.length > 0;
		}

		static string default_host(string iface_name) {
			if (iface_name.has_prefix("ICoreWebView2Controller")) {
				return "controller";
			}
			return "webview";
		}

		static void map_param(
			Parse.Parameter param,
			bool getter,
			out string c_param,
			out string vala_param,
			out string c_arg,
			out string vala_arg
		) {
			var type_ref = param.Type;
			var pname = NameMapper.to_snake(param.Name.length > 0 ? param.Name : "param");
			if (getter && type_ref.Kind == "PointerTo") {
				if (type_ref.Child != null && type_ref.Child.Name == "LPWSTR") {
					c_param = "LPWSTR *%s".printf(pname);
					vala_param = "out uint16* %s".printf(pname);
					c_arg = pname;
					vala_arg = "out %s".printf(pname);
					return;
				}
				if (type_ref.Child != null && type_ref.Child.Kind == "ApiRef" && type_ref.Child.Name == "BOOL") {
					c_param = "BOOL *%s".printf(pname);
					vala_param = "out int %s".printf(pname);
					c_arg = pname;
					vala_arg = "out val";
					return;
				}
				if (type_ref.Child != null && is_floating_type(type_ref.Child.Name)) {
					c_param = "DOUBLE *%s".printf(pname);
					vala_param = "out double %s".printf(pname);
					c_arg = pname;
					vala_arg = "out val";
					return;
				}
			}
			if (type_ref.Kind == "ApiRef" && type_ref.Name == "RECT") {
				c_param = "const RECT *%s".printf(pname);
				vala_param = "Rect %s".printf(pname);
				c_arg = "*%s".printf(pname);
				vala_arg = "g_host.bounds";
				return;
			}
			if (type_ref.Kind == "ApiRef" && type_ref.Name == "BOOL") {
				c_param = "BOOL %s".printf(pname);
				vala_param = "int %s".printf(pname);
				c_arg = pname;
				vala_arg = "visible ? 1 : 0";
				return;
			}
			if (type_ref.Kind == "ApiRef" && is_floating_type(type_ref.Name)) {
				c_param = "DOUBLE %s".printf(pname);
				vala_param = "double %s".printf(pname);
				c_arg = pname;
				vala_arg = "zoom";
				return;
			}
			if (type_ref.Kind == "ApiRef" && type_ref.Name == "LPCWSTR") {
				c_param = "LPCWSTR %s".printf(pname);
				vala_param = "[CCode(type_id = \"LPCWSTR\")] uint16* %s".printf(pname);
				c_arg = pname;
				vala_arg = string_param_vala_arg(pname);
				return;
			}
			if (type_ref.Kind == "PointerTo" && type_ref.Child != null && type_ref.Child.Name == "LPCWSTR") {
				c_param = "LPCWSTR %s".printf(pname);
				vala_param = "[CCode(type_id = \"LPCWSTR\")] uint16* %s".printf(pname);
				c_arg = pname;
				vala_arg = string_param_vala_arg(pname);
				return;
			}
			c_param = "void* %s".printf(pname);
			vala_param = "void* %s".printf(pname);
			c_arg = pname;
			vala_arg = pname;
		}

		static bool is_floating_type(string name) {
			return name == "DOUBLE" || name == "double";
		}

		static string string_param_vala_arg(string c_name) {
			switch (c_name) {
			case "html_content":
				return "WideString(html).ptr";
			case "web_message_as_json":
				return "WideString(json).ptr";
			case "uri":
				return "g_host.pending_url.ptr";
			default:
				return c_name;
			}
		}

		static string default_vala_call(
			string glue_name,
			string extern_name,
			string host,
			string[] vala_args
		) {
			if (glue_name == "put_bounds") {
				return "%s (host_controller_com(), g_host.bounds)".printf(extern_name);
			}
			var host_ref = host == "controller" ? "host_controller_com()" : "host_webview_com()";
			if (vala_args.length <= 1) {
				return "%s (%s)".printf(extern_name, host_ref);
			}
			var call_args = new Gee.ArrayList<string> ();
			call_args.add(host_ref);
			for (int i = 1; i < vala_args.length; i++) {
				call_args.add(vala_args[i]);
			}
			return "%s (%s)".printf(extern_name, string.joinv(", ", call_args.to_array()));
		}

		public static Gee.ArrayList<Parse.SyncComSpec> specs_for_entry(Parse.ErgoNativeMapEntry entry) {
			var specs = new Gee.ArrayList<Parse.SyncComSpec> ();
			if (entry.sync_com.size == 0) {
				return specs;
			}
			foreach (var spec in entry.sync_com) {
				if (spec.glue != null && spec.glue.length > 0) {
					specs.add(spec);
					continue;
				}
				foreach (var glue in WebView2GlueEmitter.glue_method_names(entry.glue)) {
					specs.add(new Parse.SyncComSpec() {
						glue = glue,
						com = spec.com,
						host = spec.host,
						vala_call = spec.vala_call,
					});
				}
			}
			return specs;
		}
	}
}
