/*
 * Emit Win32.Ui.WebView glue methods from WebView2MethodCatalog.
 */

namespace Generate {
	public class WebView2GlueEmitter : Object {
		const string GENERATED_HEADER = """/* Generated by generate-binding — do not edit. */

namespace Win32.Ui.WebView {

""";

		const string GENERATED_FOOTER = """
}

""";

		static WebView2ComSyncEmitter? sync_emitter;

		public void set_sync_emitter(WebView2ComSyncEmitter emitter) {
			sync_emitter = emitter;
		}

		public static string[] glue_method_names(string glue) {
			var local = glue;
			var dot = local.last_index_of(".");
			if (dot >= 0) {
				local = local.substring(dot + 1);
			}
			local = local.strip();
			if (local.contains(" / ")) {
				var parts = local.split(" / ");
				var names = new Gee.ArrayList<string> ();
				foreach (var part in parts) {
					names.add(part.strip());
				}
				return names.to_array();
			}
			if (local.contains("/")) {
				var slash = local.index_of("/");
				var left = local.substring(0, slash).strip();
				var right = local.substring(slash + 1).strip();
				if (right.has_prefix("get_")) {
					var suffix = right.substring(4);
					if (left == "put") {
						return { "put_" + suffix, right };
					}
				}
			}
			return { local };
		}

		public string emit_from_catalog(WebView2MethodCatalog catalog) {
			var sb = new GLib.StringBuilder(GENERATED_HEADER);
			foreach (var entry in catalog.entries) {
				if (!entry.emit_glue) {
					continue;
				}
				emit_method(sb, entry);
			}
			sb.append(GENERATED_FOOTER);
			return sb.str;
		}

		static void emit_method(GLib.StringBuilder sb, WebView2CatalogEntry entry) {
			var name = entry.glue_name;
			var kind = entry.glue_kind;
			var controller = entry.host == "controller";
			var ready_fn = controller ? "controller_ready" : "webview_ready";
			var cname = "vala_webview2_host_" + name;
			var sync = sync_emitter != null ? sync_emitter.method_for(name) : null;
			switch (kind) {
			case WebView2GlueKind.WEBVIEW_VOID:
				sb.append_printf(
					"""[CCode(cname = "%s")]
public bool %s() {
	if (!webview_ready()) {
		return false;
	}
	return com_ok(%s);
}

""",
					cname,
					name,
					sync != null ? sync.vala_call : "g_host.webview." + name + "()"
				);
				break;
			case WebView2GlueKind.WEBVIEW_STRING:
				var arg = string_param_name(name);
				sb.append_printf(
					"""[CCode(cname = "%s")]
public bool %s(string %s) {
	if (!webview_ready() || %s.length == 0) {
		return false;
	}
	return com_ok(%s);
}

""",
					cname,
					name,
					arg,
					arg,
					sync != null ? sync.vala_call : "g_host.webview." + name + "(WideString(" + arg + ").ptr)"
				);
				break;
			case WebView2GlueKind.WEBVIEW_GET_COM_STRING:
				var out_var = com_string_out_name(name);
				sb.append_printf(
					"""[CCode(cname = "%s")]
public string %s() {
	if (!webview_ready()) {
		return "";
	}
	uint16* %s = null;
	if (!com_ok(%s)) {
		return "";
	}
	return take_com_string(%s);
}

""",
					cname,
					name,
					out_var,
					sync != null ? sync.vala_call : "g_host.webview." + name + "(out " + out_var + ")",
					out_var
				);
				break;
			case WebView2GlueKind.WEBVIEW_GET_BOOL:
				sb.append_printf(
					"""[CCode(cname = "%s")]
public bool %s() {
	if (!%s()) {
		return false;
	}
	int val = 0;
	if (!com_ok(%s)) {
		return false;
	}
	return val != 0;
}

""",
					cname,
					name,
					ready_fn,
					sync != null ? sync.vala_call : "g_host.webview." + name + "(out val)"
				);
				break;
			case WebView2GlueKind.WEBVIEW_STUB:
				sb.append_printf(
					"""[CCode(cname = "%s")]
public bool %s(string js) {
	/* async COM — completed-handler wiring deferred. */
	if (!webview_ready() || js.length == 0) {
		return false;
	}
	return false;
}

""",
					cname,
					name
				);
				break;
			case WebView2GlueKind.WEBVIEW_PUT_BOOL:
				sb.append_printf(
					"""[CCode(cname = "%s")]
public bool %s(bool visible) {
	if (!%s()) {
		return false;
	}
	return com_ok(%s);
}

""",
					cname,
					name,
					ready_fn,
					sync != null ? sync.vala_call : "g_host.controller." + name + "(visible ? 1 : 0)"
				);
				break;
			case WebView2GlueKind.WEBVIEW_PUT_DOUBLE:
				sb.append_printf(
					"""[CCode(cname = "%s")]
public bool %s(double zoom) {
	if (!%s()) {
		return false;
	}
	return com_ok(%s);
}

""",
					cname,
					name,
					ready_fn,
					sync != null ? sync.vala_call : "g_host.controller." + name + "(zoom)"
				);
				break;
			case WebView2GlueKind.WEBVIEW_GET_DOUBLE:
				sb.append_printf(
					"""[CCode(cname = "%s")]
public double %s() {
	if (!%s()) {
		return 1.0;
	}
	double val = 1.0;
	if (!com_ok(%s)) {
		return 1.0;
	}
	return val;
}

""",
					cname,
					name,
					ready_fn,
					sync != null ? sync.vala_call : "g_host.controller." + name + "(out val)"
				);
				break;
			default:
				break;
			}
		}

		static string string_param_name(string glue_method) {
			switch (glue_method) {
			case "navigate_to_string":
				return "html";
			case "post_web_message_as_json":
				return "json";
			case "post_web_message_as_string":
				return "text";
			default:
				return "text";
			}
		}

		static string com_string_out_name(string glue_method) {
			switch (glue_method) {
			case "get_source":
				return "uri";
			case "get_document_title":
				return "title";
			default:
				return "com_str";
			}
		}
	}
}
