/*
 * Emit COM event handler vtables + Vala delegate bridge for ergo WebView signals.
 * Generated C follows the same layout as src/win32-ui-webview2-com-glue.c.
 */

namespace Generate {
	public class WebView2EventSpec : Object {
		public string add_method { get; set; default = ""; }
		public string remove_method { get; set; default = ""; }
		public string handler_iface { get; set; default = ""; }
		public string callback { get; set; default = ""; }
		public string invoke { get; set; default = "void"; }
		public string? args_iface { get; set; default = null; }
	}

	public class WebView2EventEmitter : Object {
		const string C_HEADER = """/* Generated by generate-binding — do not edit. */

#define COBJMACROS
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>

#include "win32-ui-webview2-events.h"
#include "win32-ui-webview2-sdk.h"

""";

		const string H_HEADER = """/* Generated by generate-binding — do not edit. */
#ifndef VALA_WIN32_UI_WEBVIEW2_EVENTS_H
#define VALA_WIN32_UI_WEBVIEW2_EVENTS_H

#include "win32-ui-webview2-sdk.h"

#ifdef __cplusplus
extern "C" {
#endif

""";

		const string H_FOOTER = """
#ifdef __cplusplus
}
#endif

#endif /* VALA_WIN32_UI_WEBVIEW2_EVENTS_H */
""";

		const string BRIDGE_HEADER = """/* Generated by generate-binding — do not edit. */

namespace Win32.Ui.WebView {

""";

		const string BRIDGE_FOOTER = """
}

""";

		public Gee.ArrayList<WebView2EventSpec> load_specs(string overrides_path) throws GLib.Error {
			var specs = new Gee.ArrayList<WebView2EventSpec> ();
			var parser = new Json.Parser();
			parser.load_from_file(overrides_path);
			var root = parser.get_root();
			if (root == null || root.get_node_type() != Json.NodeType.OBJECT) {
				return specs;
			}
			var node = root.get_object().get_member("ergo_events");
			if (node == null || node.get_node_type() != Json.NodeType.ARRAY) {
				return specs;
			}
			var arr = node.get_array();
			for (uint i = 0; i < arr.get_length(); i++) {
				var el = arr.get_element(i);
				if (el == null || el.get_node_type() != Json.NodeType.OBJECT) {
					continue;
				}
				var obj = el.get_object();
				var spec = new WebView2EventSpec();
				spec.add_method = read_string(obj, "add");
				spec.remove_method = read_string(obj, "remove");
				spec.handler_iface = read_string(obj, "handler_iface");
				spec.callback = read_string(obj, "callback");
				spec.invoke = read_string(obj, "invoke");
				if (spec.invoke.length == 0) {
					spec.invoke = "void";
				}
				spec.args_iface = read_optional_string(obj, "args_iface");
				if (spec.add_method.length > 0 && spec.handler_iface.length > 0 && spec.callback.length > 0) {
					specs.add(spec);
				}
			}
			return specs;
		}

		public void emit_files(
			string overrides_path,
			string generated_dir
		) throws GLib.Error {
			var specs = load_specs(overrides_path);
			var c_path = GLib.Path.build_filename(generated_dir, "win32-ui-webview2-events.c");
			var h_path = GLib.Path.build_filename(generated_dir, "win32-ui-webview2-events.h");
			var bridge_path = GLib.Path.build_filename(generated_dir, "win32-ui-webview2-events-bridge.vala");
			GLib.FileUtils.set_contents(c_path, emit_c(specs));
			GLib.FileUtils.set_contents(h_path, emit_h(specs));
			GLib.FileUtils.set_contents(bridge_path, emit_bridge(specs));
		}

		static string read_string(Json.Object obj, string key) {
			var node = obj.get_member(key);
			if (node != null && node.get_value_type() == typeof (string)) {
				return node.get_string();
			}
			return "";
		}

		static string? read_optional_string(Json.Object obj, string key) {
			var node = obj.get_member(key);
			if (node != null && node.get_value_type() == typeof (string)) {
				return node.get_string();
			}
			return null;
		}

		string emit_c(Gee.ArrayList<WebView2EventSpec> specs) {
			var sb = new GLib.StringBuilder(C_HEADER);
			sb.append("""
typedef struct {
	void *handler;
	EventRegistrationToken token;
	BOOL registered;
} WebView2EventSlot;

""");
			for (int i = 0; i < specs.size; i++) {
				emit_handler_struct(sb, specs[i], i);
			}
			if (specs.size > 0) {
				sb.append_printf("static WebView2EventSlot g_event_slots[%u];\n\n", specs.size);
			}
			for (int i = 0; i < specs.size; i++) {
				emit_handler_impl(sb, specs[i], i);
			}
			emit_register(sb, specs);
			emit_unregister(sb, specs);
			return sb.str;
		}

		static void emit_handler_struct(GLib.StringBuilder sb, WebView2EventSpec spec, int index) {
			var handler_type = spec.handler_iface;
			var vtbl_type = handler_type + "Vtbl";
			sb.append_printf("""
typedef struct WebView2EventHandler%u {
	%s iface;
	%s vtbl;
	LONG ref_count;
} WebView2EventHandler%u;

""",
				index,
				handler_type,
				vtbl_type,
				index
			);
		}

		static void emit_handler_impl(GLib.StringBuilder sb, WebView2EventSpec spec, int index) {
			var handler_type = spec.handler_iface;
			var iid = "IID_" + spec.handler_iface;
			var addref_fn = handler_type + "_AddRef";
			sb.append_printf("""
static HRESULT STDMETHODCALLTYPE event_handler%u_qi (
	%s *This,
	REFIID riid,
	void **ppv)
{
	if (IsEqualIID (riid, &IID_IUnknown)
	    || IsEqualIID (riid, &%s)) {
		*ppv = This;
		%s (This);
		return S_OK;
	}
	*ppv = NULL;
	return E_NOINTERFACE;
}

static ULONG STDMETHODCALLTYPE event_handler%u_addref (
	%s *This)
{
	WebView2EventHandler%u *self = (WebView2EventHandler%u *) This;
	return (ULONG) InterlockedIncrement (&self->ref_count);
}

static ULONG STDMETHODCALLTYPE event_handler%u_release (
	%s *This)
{
	WebView2EventHandler%u *self = (WebView2EventHandler%u *) This;
	LONG count = InterlockedDecrement (&self->ref_count);
	if (count == 0) {
		CoTaskMemFree (self);
	}
	return (ULONG) count;
}

""",
				index,
				handler_type,
				iid,
				addref_fn,
				index,
				handler_type,
				index,
				index,
				index,
				handler_type,
				index,
				index
			);
			emit_invoke(sb, spec, index);
		}

		static void emit_invoke(GLib.StringBuilder sb, WebView2EventSpec spec, int index) {
			var handler_type = spec.handler_iface;
			var args_type = spec.args_iface ?? "IUnknown";
			var body = "";
			switch (spec.invoke) {
			case "bool_get_is_success":
				body = """
	BOOL success = FALSE;
	if (args != NULL) {
		%s_get_IsSuccess (args, &success);
	}
	%s (success ? 1 : 0);
""".printf(spec.args_iface, spec.callback);
				break;
			default:
				body = "\t%s ();\n".printf(spec.callback);
				break;
			}
			sb.append_printf("""
static HRESULT STDMETHODCALLTYPE event_handler%u_invoke (
	%s *This,
	ICoreWebView2 *sender,
	%s *args)
{
	(void) This;
	(void) sender;
%s	return S_OK;
}

""",
				index,
				handler_type,
				args_type,
				body
			);
		}

		static void emit_register(GLib.StringBuilder sb, Gee.ArrayList<WebView2EventSpec> specs) {
			sb.append("""
void vala_webview2_events_register (ICoreWebView2 *webview)
{
	HRESULT hr;

	if (webview == NULL) {
		return;
	}
""");
			for (int i = 0; i < specs.size; i++) {
				var spec = specs[i];
				var add_macro = "ICoreWebView2_" + spec.add_method;
				var handler_type = spec.handler_iface;
				var release_fn = handler_type + "_Release";
				sb.append_printf("""
	if (!g_event_slots[%d].registered) {
		WebView2EventHandler%d *handler = (WebView2EventHandler%d *) CoTaskMemAlloc (sizeof (WebView2EventHandler%d));
		if (handler != NULL) {
			ZeroMemory (handler, sizeof (*handler));
			handler->iface.lpVtbl = &handler->vtbl;
			handler->vtbl.QueryInterface = event_handler%d_qi;
			handler->vtbl.AddRef = event_handler%d_addref;
			handler->vtbl.Release = event_handler%d_release;
			handler->vtbl.Invoke = event_handler%d_invoke;
			handler->ref_count = 1;
			hr = %s (webview, &handler->iface, &g_event_slots[%d].token);
			if (SUCCEEDED (hr)) {
				g_event_slots[%d].handler = handler;
				g_event_slots[%d].registered = TRUE;
			} else {
				fprintf (stderr, "WebView2 %s failed: 0x%%08lx\n", (unsigned long) hr);
				%s (&handler->iface);
			}
		}
	}
""",
					i,
					i,
					i,
					i,
					i,
					i,
					i,
					i,
					add_macro,
					i,
					i,
					i,
					spec.add_method,
					release_fn
				);
			}
			sb.append("}\n\n");
		}

		static void emit_unregister(GLib.StringBuilder sb, Gee.ArrayList<WebView2EventSpec> specs) {
			sb.append("""
void vala_webview2_events_unregister (ICoreWebView2 *webview)
{
	if (webview == NULL) {
		return;
	}
""");
			for (int i = 0; i < specs.size; i++) {
				var spec = specs[i];
				var remove_macro = "ICoreWebView2_" + spec.remove_method;
				var handler_type = spec.handler_iface;
				var release_fn = handler_type + "_Release";
				sb.append_printf("""
	if (g_event_slots[%d].registered) {
		%s (webview, g_event_slots[%d].token);
		if (g_event_slots[%d].handler != NULL) {
			%s ((%s *) g_event_slots[%d].handler);
			g_event_slots[%d].handler = NULL;
		}
		g_event_slots[%d].registered = FALSE;
	}
""",
					i,
					remove_macro,
					i,
					i,
					release_fn,
					handler_type,
					i,
					i,
					i
				);
			}
			sb.append("}\n");
		}

		string emit_h(Gee.ArrayList<WebView2EventSpec> specs) {
			var sb = new GLib.StringBuilder(H_HEADER);
			sb.append("""
void vala_webview2_events_register (ICoreWebView2 *webview);

void vala_webview2_events_unregister (ICoreWebView2 *webview);

""");
			foreach (var spec in specs) {
				if (spec.invoke == "bool_get_is_success") {
					sb.append_printf("void %s (int success);\n\n", spec.callback);
				} else {
					sb.append_printf("void %s (void);\n\n", spec.callback);
				}
			}
			sb.append(H_FOOTER);
			return sb.str;
		}

		string emit_bridge(Gee.ArrayList<WebView2EventSpec> specs) {
			var sb = new GLib.StringBuilder(BRIDGE_HEADER);
			var seen_callbacks = new Gee.HashSet<string> ();
			foreach (var spec in specs) {
				if (seen_callbacks.contains(spec.callback)) {
					continue;
				}
				seen_callbacks.add(spec.callback);
				emit_bridge_callback(sb, spec);
			}
			sb.append(BRIDGE_FOOTER);
			return sb.str;
		}

		static void emit_bridge_callback(GLib.StringBuilder sb, WebView2EventSpec spec) {
			var bind_name = bind_method_name(spec.callback);
			var signal = signal_name_from_callback(spec.callback);
			var delegate_type = signal + "Delegate";
			var handler_var = bind_name + "_handler";
			var cb_name = signal + "_cb";
			if (spec.invoke == "bool_get_is_success") {
				sb.append_printf("""
public delegate void %s (bool success);

static %s? %s;

public static void %s (%s? handler) {
	%s = handler;
}

[CCode(cname = "%s")]
public static void %s (int success) {
	if (%s != null) {
		%s (success != 0);
	}
}

""",
					delegate_type,
					delegate_type,
					handler_var,
					bind_name,
					delegate_type,
					handler_var,
					spec.callback,
					cb_name,
					handler_var,
					handler_var
				);
			} else {
				sb.append_printf("""
public delegate void %s ();

static %s? %s;

public static void %s (%s? handler) {
	%s = handler;
}

[CCode(cname = "%s")]
public static void %s () {
	if (%s != null) {
		%s ();
	}
}

""",
					delegate_type,
					delegate_type,
					handler_var,
					bind_name,
					delegate_type,
					handler_var,
					spec.callback,
					cb_name,
					handler_var,
					handler_var
				);
			}
		}

		static string bind_method_name(string callback) {
			var name = callback;
			if (name.has_prefix("vala_webview2_emit_")) {
				name = name.substring(19);
			}
			return "bind_" + name;
		}

		static string signal_name_from_callback(string callback) {
			var name = callback;
			if (name.has_prefix("vala_webview2_emit_")) {
				return name.substring(19);
			}
			return name;
		}
	}
}
