/*
 * Emit generated/win32-wide-strings.vala from template(G3).
 */

namespace Generate {
	public class WideStringsEmitter : Object {
		const string GENERATED_HEADER = """/* Generated by generate-binding — do not edit. */

""";

		public string emit_from_template(string template_path) throws GLib.Error {
			string body;
			GLib.FileUtils.get_contents(template_path, out body);
			body = strip_template_preamble(body);
			return GENERATED_HEADER + body;
		}

		static string strip_template_preamble(string body) {
			if (!body.has_prefix("/*")) {
				return body;
			}
			var end = body.index_of("*/");
			if (end < 0) {
				return body;
			}
			var i = end + 2;
			while (i < body.length) {
				var c = body[i];
				if (c != '\n' && c != '\r') {
					break;
				}
				i++;
			}
			return body.substring(i);
		}
	}
}