/*
 * Emit Track B ergonomic widget layer (namespace Win32) from a Vala template.
 * B3: convention + hardcoded dispatch table — not win32json-driven yet.
 */

namespace Generate {
	public class WidgetEmitter : Object {
		const string GENERATED_HEADER = """/* Generated by generate-binding — do not edit. */

""";

		public string emit_from_template (string template_path) throws GLib.Error {
			string body;
			GLib.FileUtils.get_contents (template_path, out body);
			body = strip_template_preamble (body);
			return GENERATED_HEADER + body;
		}

		static string strip_template_preamble (string body) {
			if (!body.has_prefix ("/*")) {
				return body;
			}
			var end = body.index_of ("*/");
			if (end < 0) {
				return body;
			}
			var i = end + 2;
			while (i < body.length) {
				var c = body[i];
				if (c != '\n' && c != '\r') {
					break;
				}
				i++;
			}
			return body.substring (i);
		}
	}
}
