/* Generated by generate-binding — do not edit. */

[CCode (cprefix = "", cheader_filename = "WebView2.h")]
namespace Microsoft.Web.WebView2.Win32 {
	[CCode (cname = "INT", has_type_id = false)]
	public enum COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT {
		[CCode (cname = "COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG")]
		COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG = 0,
		[CCode (cname = "COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_JPEG")]
		COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_JPEG = 0,
	}

	[CCode (cname = "INT", has_type_id = false)]
	public enum COREWEBVIEW2_MOVE_FOCUS_REASON {
		[CCode (cname = "COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC")]
		COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC = 0,
		[CCode (cname = "COREWEBVIEW2_MOVE_FOCUS_REASON_NEXT")]
		COREWEBVIEW2_MOVE_FOCUS_REASON_NEXT = 0,
		[CCode (cname = "COREWEBVIEW2_MOVE_FOCUS_REASON_PREVIOUS")]
		COREWEBVIEW2_MOVE_FOCUS_REASON_PREVIOUS = 0,
	}

	[CCode (cname = "INT", has_type_id = false)]
	public enum COREWEBVIEW2_WEB_ERROR_STATUS {
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_UNKNOWN")]
		COREWEBVIEW2_WEB_ERROR_STATUS_UNKNOWN = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT")]
		COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_EXPIRED")]
		COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_EXPIRED = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS")]
		COREWEBVIEW2_WEB_ERROR_STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_REVOKED")]
		COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_REVOKED = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_IS_INVALID")]
		COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_IS_INVALID = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_SERVER_UNREACHABLE")]
		COREWEBVIEW2_WEB_ERROR_STATUS_SERVER_UNREACHABLE = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_TIMEOUT")]
		COREWEBVIEW2_WEB_ERROR_STATUS_TIMEOUT = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE")]
		COREWEBVIEW2_WEB_ERROR_STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_ABORTED")]
		COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_ABORTED = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_RESET")]
		COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_RESET = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_DISCONNECTED")]
		COREWEBVIEW2_WEB_ERROR_STATUS_DISCONNECTED = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_CANNOT_CONNECT")]
		COREWEBVIEW2_WEB_ERROR_STATUS_CANNOT_CONNECT = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_HOST_NAME_NOT_RESOLVED")]
		COREWEBVIEW2_WEB_ERROR_STATUS_HOST_NAME_NOT_RESOLVED = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED")]
		COREWEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_REDIRECT_FAILED")]
		COREWEBVIEW2_WEB_ERROR_STATUS_REDIRECT_FAILED = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_UNEXPECTED_ERROR")]
		COREWEBVIEW2_WEB_ERROR_STATUS_UNEXPECTED_ERROR = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_VALID_AUTHENTICATION_CREDENTIALS_REQUIRED")]
		COREWEBVIEW2_WEB_ERROR_STATUS_VALID_AUTHENTICATION_CREDENTIALS_REQUIRED = 0,
		[CCode (cname = "COREWEBVIEW2_WEB_ERROR_STATUS_VALID_PROXY_AUTHENTICATION_REQUIRED")]
		COREWEBVIEW2_WEB_ERROR_STATUS_VALID_PROXY_AUTHENTICATION_REQUIRED = 0,
	}

	[CCode (cname = "EventRegistrationToken")]
	public struct EventRegistrationToken {
		public long value;
	}

	[CCode (cheader_filename = "objbase.h", cname = "IUnknown", ref_function = "", unref_function = "")]
	public interface IUnknown {
		[CCode (cname = "QueryInterface")]
		public abstract int query_interface (void* riid, void** ppv_object);

		[CCode (cname = "AddRef")]
		public abstract uint add_ref ();

		[CCode (cname = "Release")]
		public abstract uint release ();
	}


	[CCode (cname = $(VapiEmitter.quoted_c_string (t.Name)), ref_function = "", unref_function = "")]
	public interface $(t.Name) : $(parent) {


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);

	}


	[CCode (cname = $(VapiEmitter.quoted_c_string (t.Name)), ref_function = "", unref_function = "")]
	public interface $(t.Name) : $(parent) {


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);

	}


	[CCode (cname = $(VapiEmitter.quoted_c_string (t.Name)), ref_function = "", unref_function = "")]
	public interface $(t.Name) : $(parent) {


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);

	}


	[CCode (cname = $(VapiEmitter.quoted_c_string (t.Name)), ref_function = "", unref_function = "")]
	public interface $(t.Name) : $(parent) {


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);

	}


	[CCode (cname = $(VapiEmitter.quoted_c_string (t.Name)), ref_function = "", unref_function = "")]
	public interface $(t.Name) : $(parent) {


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);

	}


	[CCode (cname = $(VapiEmitter.quoted_c_string (t.Name)), ref_function = "", unref_function = "")]
	public interface $(t.Name) : $(parent) {


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);

	}


	[CCode (cname = $(VapiEmitter.quoted_c_string (t.Name)), ref_function = "", unref_function = "")]
	public interface $(t.Name) : $(parent) {


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);

	}


	[CCode (cname = $(VapiEmitter.quoted_c_string (t.Name)), ref_function = "", unref_function = "")]
	public interface $(t.Name) : $(parent) {


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


			$(ptype) $(pname)$(comma)


		);

	}


	[CCode (cname = $(VapiEmitter.quoted_c_string (t.Name)), ref_function = "", unref_function = "")]
	public interface $(t.Name) : $(parent) {


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);


		[CCode (cname = $(VapiEmitter.quoted_c_string (method.Name)))]
		public abstract $(ret) $(vala_name) (


			$(ptype) $(pname)$(comma)


		);

	}

}
