#!/usr/bin/env bash
# Regenerate src/win32-ui-webview2-host.h (Vala cross-unit include for host shell).
set -euo pipefail
ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
cd "$ROOT"

out="$ROOT/src/win32-ui-webview2-host.h"
cat > "$out" <<'EOF'
/* Generated by scripts/regen-webview2-host-header.sh — do not edit.
 * Cross-unit include for Vala sources that use Win32.Ui.WebView from src/win32-ui-webview2-host.vala.
 * Keep minimal: each .c unit emits its own symbol declarations and WideString layout. */

#ifndef VALA_WIN32_UI_WEBVIEW2_HOST_H
#define VALA_WIN32_UI_WEBVIEW2_HOST_H

#include <stdbool.h>
#include <stdint.h>
#include <win32-ui-webview2-sdk.h>

#endif
EOF

echo "wrote $out"
